### ISSUE TITLE
Feature request: Disable history completly

### ISSUE THREAD

**Issue by 01-Scripts** [zxing/zxing#103]
Hi,

I'm using the Barcode Scanner App on Android an I'm loving it.
But my question is:
Is it possible to add a setting to disable the history of scanned barcodes completly?

Regards

**Comment by AthraaOil** [comment]
Hi,

I have used zxing to scan barcode and Qr code from web, but the it does not scan small barcode from camera of mobile because there is no focus or zoom to scan the small size.
and this is the library that I have used 
<script type="text/javascript" src="https://unpkg.com/@zxing/library@latest/umd/index.min.js"></script>
