### ISSUE TITLE
Abuse of unicode can lead to very convincing phishing links

### ISSUE THREAD

**Issue by Plazmaz** [zxing/zxing#1050]
Hi, I just wanted to let you know that your scanner doesn't do a good job of handling unicode, which leads to some nasty possibilities around malicious links. For instance, here's two screenshots, both of which lead to my site if clicked:

![image](https://user-images.githubusercontent.com/1331014/43690692-4eca42d6-98c3-11e8-9a4d-28b32f7a54a4.png)
![image](https://user-images.githubusercontent.com/1331014/43690693-51fac02a-98c3-11e8-8120-ad5cb6913a4f.png)

The first link is abusing an RTL character and is actually
(\u202e)https://dylankatz.com/moc.elgoog.www
This can be fixed by replacing whitespace unicode characters with spaces.

The second link abuses a character that looks like a slash and is actually:
http://www.google.xn--comsearchquery-iu3hgf.dktz.co
when rendered to punycode

**Comment by srowen** [comment]
Yes it's a good point. I think the best thing is to not recognize these as URIs at all; the unicode should make them invalid as URIs anyway. There are other cases of URIs that are even technically valid but sneaky like "https://www.google.com@evil.com/...".

There was even code to handle the latter, but was never used. That can be reactivated.

That will prevent it from showing the option to open the link. I don't know that it will stop Android from linkifying the text though. It seems to do so anyway judging by your example. I don't know of a way around that other than turning it off, but that is quite useful functionality.

**Comment by Plazmaz** [comment]
@srowen converting links to their punycode equivalents is a good method for preventing homoglyph attacks. As for the RTL character, just strip any non-whitespace unicode characters. Those are the two best approaches to resolving these issues.

**Comment by srowen** [comment]
Changing/stripping these characters might not be valid -- unicode text itself is legitimate and should just be shown as that text. If it's true that changing/stripping results in a string that could be construed as a URI, is it proper to assume it was trying to be a URI? Otherwise we get into defining what constitutes a URI that isn't valid but was trying to be in a malicious way, so that only that is modified. I think just not pretending they're URIs in the interface helps noticeably. I did that at https://github.com/zxing/zxing/commit/2179c52ee3e18ddc7e3fc2e9cd8237a60315ea28

**Comment by Plazmaz** [comment]
@srowen Ah okay, yep, I think that's a valid approach. Since this is also a library, do you think would this warrant CVE assignment? I know apple has issued CVEs for similar bugs (https://nvd.nist.gov/vuln/detail/CVE-2018-4187).
