### ISSUE TITLE
BarcodeScanner 4.7.8 regression: camera LED stays off

### ISSUE THREAD

**Issue by Andreas-Filsinger** [zxing/zxing#1075]
On quite old devices (Android 5.1.1. with is a Samsung Galaxy Xcover 3 G388F) BarcodeScanner 4.7.8 can not activate the LED anymore. This is all fine at 4.7.7. and below.

On Android 6.0.1 this is no issue (Samsung Galaxy XCover VE, G389F), BarcodeScanner 4.7.8 has no problem here.

**Comment by srowen** [comment]
I think this is another instance of bugs in camera drivers. Another person reported something related, that focus didn't work, and it was due to this change: https://github.com/zxing/zxing/commit/c3d649f6abe39f121ecedc9ea2e269152899fda6#diff-c31b32364ce19ca8fcd150a417ecce58 But that camera API call is entirely correct, and even helps work around a different issue. Yet I've seen for just about any camera API call, some phone/software combo out there hits an error when using it. This so far looks below the threshold of having a whole new workaround.

**Comment by Andreas-Filsinger** [comment]
Yes, i also viewed all the (100+) commits between .7 and .8 - i saw this "nexus camera" fix, but coud not imagine that this single line can be so destructiv (in combination with a buggy implemented camera API). 
Not an easy task to deal every soul right in this huge chicken farm (of camera implementations). No Problem for me to use 4.7.7 on such old devices!! Thanks for this great software.
Andreas
