### ISSUE TITLE
On some older phones the app crashes with an error after 5 to 20 scans

### ISSUE THREAD

**Issue by FrankFinken** [zxing/zxing#1081]
Hi,

I'm using the ZXing app for scanning and after the last update some of my older phones get an error after about 5 to 20 scans. It is the message "Sorry, the Android camera encountered a problem. You may need to restart the device" The only solution is indeed restarting the phone.

Error occurs on three Samsung S3 phones and one Samsung J3 phone.

Other phones do not have the issue. 
If I reinstall com.google.zxing.client.android-4.7.3-103-minAPI15.apk it all works again for all phones.
Not much to go on, but I hope you can fix this...

Regards,
Frank

**Comment by srowen** [comment]
Yeah, that means an error from the camera driver rather than the app. I don't see any crashes that are common in the console, so likely specific to a few old phones. For really old Android you need to use older builds of the app anyway

**Comment by FrankFinken** [comment]
But a reinstall of com.google.zxing.client.android-4.7.3-103-minAPI15.apk fixes the issue. That would argue against a camera driver error. And the Samsung J3 is on Android 7

**Comment by srowen** [comment]
Typically it's because of some camera config that the app sets in the new version, and correctly. It can trigger a problem that wasn't observed previously. Here I wonder if the latest requires a newer Android, too, as you are installing some other build that was manually modified to work with older Android.
