### ISSUE TITLE
4.7.8: Scanner doesn't scan codes

### ISSUE THREAD

**Issue by sivaraam** [zxing/zxing#1115]
I was using the app for a long time from F-droid. I upgraded to 4.7.8 some time ago. Since then I'm unable to scan bar codes and QR codes using the app. Not sure why but the success rate for scanning a bar code in my attempts is roughly 1 in about 15 and almost 0 for QR codes.

Also, the preview of the bar codes for which scanning succeeds doesn't seem nice either. (Unfortunately I don't have a screen shot to share currently.)

I could verify that I am able to successfully scan codes both bar codes and QR codes in 4.7.7. The issue occurs on a Samsung Galaxy J1 ace running Android 5.1.1. Let me know if any other information is required.

**Comment by sivaraam** [comment]
It would have been nice if you have mentioned what's wrong with the bug report. I've seen the notice that the project is in maintenance mode but the bug report template stated only bug reports **without inadequate information** would be closed that too with request for information. I'm not sure if anything is missing. If something is I have mentioned to let me know.

BTW, I should have mentioned I filed this bug not in the hope that it would be fixed. I mostly filed it as a reference for those who wonder in the future (include the future me) why the app isn't working on Android 5.1.1. So mentioning at least why the app wouldn't work would be useful to know why the bug report is valid.

Note: I just recently verified that the app(4.7.8) works on a Moto G5(S) Plus running Android 8.

**Comment by srowen** [comment]
There is just no development going on here. See the first part of the CONTRIBUTING.md file. I'd only look at a pull request, really, unless it was a simple easy fix I could figure out in 15 minutes. As you may see from a bunch of closed reports, these types of issues are virtually always because of device bugs, which can get triggered by different use of the camera API. I have no consistent crash reports and this works on millions of devices. F-Droid is also not where the 'official' build gets released, so I can't speak to what is released there.

**Comment by sivaraam** [comment]
>  I'd only look at a pull request, really, unless it was a simple easy fix I could figure out in 15 minutes.

In that case you should better update the issue template which states: 

> Inadequate
bug reports will be closed with a request for more information.
>
> Bug reports without an associated pull request are not likely to be addressed, but will be
left open for some time to see if anyone can contribute a solution.


> As you may see from a bunch of closed reports, these types of issues are virtually always because of device bugs, which can get triggered by different use of the camera API.

Juat for the note, I'm not sure how this is a device bug as the 2.7.7 version works fine but 2.7.8 doesn't.

> I have no consistent crash reports and this works on millions of devices. 

I'm also not sure how you would get a crash report when the issue is that the app doesn't scan codes and not that the app crashes when trying to scan codes.

> F-Droid is also not where the 'official' build gets released, so I can't speak to what is released there.

That's interesting. I didn't know the F-droid version wasn't released officially. There was no note there. Anyways, I tried the play store version too and it couldn't scan the codes too.

**Comment by sivaraam** [comment]
Just to add another note, at the random times in which the app sucessfully scans the Barcode the following is screen shot of how the screen shown after scanning looks in v2.7.8. See how the preview is very bad.

![2_7_8-random-scans-preview-incorrect](https://user-images.githubusercontent.com/12448084/49790377-0b17f600-fd54-11e8-959e-dfd8bb9f4e0e.png)

The following is the same bar code scanned in v2.77 (just for reference):

![2_7_7-correct-quick-scan](https://user-images.githubusercontent.com/12448084/49790421-23881080-fd54-11e8-9d8d-e55259a8c4e7.png)

I would like to re-iterate that I'm commenting mostly only to document what I observe in the appropriate place. Not acting upon it is not an issue :

**Comment by srowen** [comment]
I updated CONTRIBUTING.md to say bug reports only, and pretty much needs a pull request.

Here's the scenario I have seen over and over in 10 years:
- App calls camera API function correctly (i.e. checks if support exists if possible, then sets it)
- Some device's driver doesn't support the function actually. This has happened more often in Cyanogen mod ROMs where maybe the metadata wasn't updated correctly to reflect device capability. Not the issue here.
- Device driver errors and fails to set any settings, including things like autofocus
- App runs but without any correct camera config, and scanning doesn't work well

Yes, in some cases it manifests in a crash, but the above scenario won't, and that's what's probably happening here.

I am pretty sure it's this line: 
https://github.com/zxing/zxing/blob/0cf3b9be71680f50c90a71ca26ce0d33664b0dd6/android/src/com/google/zxing/client/android/camera/CameraConfigurationManager.java#L184

This was added to fix another problem. it however is a fine API call.
I can't update the app on Play anymore anyway, regardless. If you like you can comment it out and build locally.

I don't control any other releases; what's on F-Droid really ought to be marked as much. Amazon released a version of it similarly and did make a note that it's not official when asked.

The problem is really hundreds of clone releases out there with ads, not these things. In retrospect releasing as open source had a number of downsides.

Now at last to your screen shots. It does look like a camera config problem, as that kind of thing indicates that it didn't set the preview size correctly. It's not auto-focus on this case.

**Comment by sivaraam** [comment]
Thanks for the information! That cleared up the confusion a little.

> I don't control any other releases; what's on F-Droid really ought to be marked as much. 

I've [filed an issue](https://gitlab.com/fdroid/fdroiddata/issues/1470) for that.
