### ISSUE TITLE
about DataMatrix Reader issue.

### ISSUE THREAD

**Issue by czh0221** [zxing/zxing#117]
As shown in figure: http://2.bp.blogspot.com/_5lL1y9ELMFM/RuqSvwzuNrI/AAAAAAAAAkw/cBNhZnGfFbY/s400/media_guru_Cool_Datamatrix.png
It is cool - data - matrix.
When I try to scan it, sometimes can't identify.
Whether because the party is the difference between point and dot?

**Comment by mig82** [comment]
Is there a filter or something we can use on the immage to make it valid? Why is it not a valid data matrix? Is it because it uses dots instead of squares? I've seen this dotted data matrix punched on the packaging of groceries. There must be an algorithm capable of reading them.

**Comment by mig82** [comment]
I've found that adding a blur to a dotted data matrix makes it readable using ZXing. Please have a look at my question in StackOverflow here (and help me find an answer if you can):

https://stackoverflow.com/questions/48908115/scan-a-dotted-laser-dot-peen-data-matrix-with-zxing

**Comment by axxel** [comment]
The current data matrix decoder fails to decode that particular example because it is a 'perfectly' oriented and sampled dot matrix. The problem is the WhiteRectDetector. It finds a white rectangle inside the code, similar to [this issue](https://github.com/glassechidna/zxing-cpp/issues/42).

If you rotate the image slightly (say 10°) or you blur it as you did or you did a suitably sized pixel dilation followed by an erosion, you'll get something that should (mostly) be detectable.
