### ISSUE TITLE
Error "The image you uploaded could not be decoded, or was too large"

### ISSUE THREAD

**Issue by dedosmedia** [zxing/zxing#1192]
Hi!
I am trying to decode some QR codes, but I am just getting this error: "The image you uploaded could not be decoded, or was too large. Go "Back" in your browser and try another image."

What is wrong with these QR codes? I can read and decode them using "Barcode Scanner" App. I am not having the same result when trying "ZXing decoder online"

https://s3.amazonaws.com/event-system-qr/OGE/1563205967509-TAEH6ZCLM.png
https://s3.amazonaws.com/event-system-qr/OGE/1563201865250-W-J01FKGX.png
https://s3.amazonaws.com/event-system-qr/OGE/1563203458016-J671U5VC8.png
https://s3.amazonaws.com/event-system-qr/OGE/1563205581789-91C5MIDA0.png
https://s3.amazonaws.com/event-system-qr/OGE/1563205967509-TAEH6ZCLM.png
https://s3.amazonaws.com/event-system-qr/OGE/1563796394390-71LV-B705.png

All those codes ar V1 codes, so there is not an alignment mark. 

I appreciate anyone help

**Comment by srowen** [comment]
Usually this means that the QR code is OK because the app scans it. However these particular images may not, ironically, as they are yielding some false-positive detection of a finder pattern that stops the recognition. A slightly different image works fine. 

However I'm not seeing that online. For example one image decodes as '1563205967509-TAEH6ZCLM'. At least one I spot checked seemed OK.

This generally isn't anything I'll act on, unless you have a pull request that fixes some clear bug.

**Comment by dedosmedia** [comment]
Thanks!.. Yeah, I see it works when I upload the image from disk, but not when I type in the URL.
Thanks so much for your help.

**Comment by Punkroku** [comment]
hello I am the wrong respondant.. I was the one that told you about
tiny.cc/oitoken and binary scoring counting its like the slash 4X then
Horizontal Slash for 5 except the horizontal slashes are binary
multiples of 5 so 5 10 20 40 values for top slash, top mid slash, bot
mid slash, bottom slash, respectively.

Tiny.cc/openInvent1 openInvent Digest Vol. 1

openInvent.club
openInvent.co - my voice and aec-guitar

I tried to make tiny.cc/oifont and put it on symbols.com or
opengameart.org but I think it was hacked or incorrect font somehow.
