### ISSUE TITLE
 Problem with PlanarYUVLuminanceSource

### ISSUE THREAD

**Issue by Caij** [zxing/zxing#1200]
PlanarYUVLuminanceSource
```
  @Override
  public byte[] getMatrix() {
    int width = getWidth();
    int height = getHeight();

    if (width == dataWidth && height == dataHeight) {
      return yuvData;
    }

    int area = width * height;
    byte[] matrix = new byte[area];
    int inputOffset = top * dataWidth + left;

    if (width == dataWidth) {
      System.arraycopy(yuvData, inputOffset, matrix, 0, area);
      return matrix;
    }

    for (int y = 0; y < height; y++) {
      int outputOffset = y * width;
      System.arraycopy(yuvData, inputOffset, matrix, outputOffset, width);
      inputOffset += dataWidth;
    }
    return matrix;
  }
```
When crop size and yuv size are the same， the returned data yuv complete data[witdh * height * 3 / 2]。
When the crop size and yuv size are not the same, the data of the returned data yuv of Y [witdh * height]

**Comment by srowen** [comment]
The first 2/3 of the bytes are the luminance (Y) and that's all that is of interest here. Yes it returns the full backing byte array if there is no crop rather than allocate/copy to a new buffer, as an optimization. This means the caller has to only use the first width x height bytes, but it appears that is the case. I don't think it's a problem, but reopen if you believe it causes an issue. Comments in the code do say this is the case.
