### ISSUE TITLE
Is there plan to switch to Camera2 implementation?

### ISSUE THREAD

**Issue by hanabi1224** [zxing/zxing#1222]
Bringing https://github.com/zxing/zxing/issues/675 back, per Android official document, Camera api has been deprecated since api version 21, and latest zxing sdk required sdk version 24+,  should it be a valid request to switch to Camera2/camerax api?

**Comment by srowen** [comment]
There's no plan to do any development on this project going forward; see the README.
Actually the app requires 19 and targets 22; it can't target 23+because of the new permissions model. However it should still work on the latest, 29.
Camera2 requires API 21. Requiring API 21 means dropping support for 19 and 20, which isn't a big deal now. If someone did all the work to rewrite it entirely for Camera2, I'd look at it.
That said, I don't know if there's much upside to Camera2 given how the camera is used here.
