### ISSUE TITLE
Code128Reader misses barcode with higher DPI images

### ISSUE THREAD

**Issue by wojciechklicki** [zxing/zxing#1265]
Hi,

I've got problem with Code128Reader when processing some images that are extracted from PDF files using 300 DPI resolution. 

Example project that show reported behaviour:
https://github.com/wojciechklicki/zxing-barcode-problem

When test_bad_prep.png (300 DPI) is processed no barcode is found, but when we process test_ok_prep.png (200 DPI) it works.

I expect that higher DPI should be better for extraction, but in this case is not.

This is quite bad for us because some other scans when done in 200 DPI are too poor quality and Code128Reader can't extract them properly.

**Comment by srowen** [comment]
The problem is that higher resolution images can reveal noise more easily too, and noise trips up detection of runs of dark and light pixels when finding the barcode bars. Lower resolution still has plenty of signal but tends to lose the noise detail first. It's just how it is for images like this. You can try preprocessing by applying a light blur or downsampling if recognition fails.
