### ISSUE TITLE
Small QR code with low error correction and camera close to it - scanning problems

### ISSUE THREAD

**Issue by leoshusar** [zxing/zxing#1300]
Hello, I don't know how to properly define it, so that issue title is not great. Maybe this isn't even really an issue - I'd just like to know what could be wrong.

I am generating small qr codes with strings like `1:A:1:3:500` and printing them on labels, each code is no smaller than 2x2 cm. Then I'm putting those labels on shelves.

However those codes are close to each other and I have to bring the camera really close so I scan only the one code I need. I'm so close that code is on full screen (like [this](https://i.ibb.co/4fvz7B2/Screenshot-20200704-140156.jpg)) and it has problems with scanning it - I have to get the camera much further, then it scans it immediately.

What is strange for me is when I set error correction to highest and print the same sized codes, it scans them much better. Same place with camera really close.

I'd just like to know what could be the reason for this behavior? Also since my native camera app works well in the same (and much worse) conditions and even with unfocused / blurry code.

**Comment by srowen** [comment]
The app in this project only scans within the reticle at the center, so that you aren't so close that autofocus can't focus. I'd check it's actually auto-focusing and try some of the camera workarounds in settings if not.

I think part of the issue is that the data is so small that you generate version 1 codes, which are so small that they do not have an alignment pattern at the bottom right. More data or EC probably makes it a version 2 code with alignment pattern and that's a bit easier to scan. That's probably a good idea.

**Comment by axxel** [comment]
What I believe might also be involved is the limitation of the `HybridBinarizer` with respect to the resolution of the image. The problem is that it tends to fail if the module size is too large. Generally it works best if you have not more than maybe 8 pixels per module (the width of the smallest black square in your code). If you spread the code across the whole sensor you might run into this problem. If you have that under control, try to sub-sample your image before feeding it to the library.

**Comment by leoshusar** [comment]
That thing with code version is true, when I set higher EC, then there appears that alignment pattern, so I believe this could be the main reason.

But thank you both, guys!
