### ISSUE TITLE
Can not scan EAN-5 and EAN-2 extension barcodes.

### ISSUE THREAD

**Issue by DevarshiShah1993** [zxing/zxing#1339]
I am trying to scan barcodes which have EAN-5 and EAN-2 extensions but it only scan first part.
![unnamed](https://user-images.githubusercontent.com/55939550/102486905-c1bfb700-408f-11eb-8777-3035b403c36e.jpg)

**Comment by srowen** [comment]
It will scan for them, but, if it isn't found, will just return the main barcode. After all it may not be there - can't know whether it was present but not found or not present.

I could imagine adding a hint that would tell it there is definitely an extension present, and fail if not found.

But this particular image may be somewhat hard to decode because of the resolution and multiple barcodes.
