### ISSUE TITLE
This is now Adware Malware

### ISSUE THREAD

**Issue by Griftaz** [zxing/zxing#1345]
This now causes Chrome (likely any default browser) to open when the phone is unlocked to one of several redirect sites detailed here:
https://forums.malwarebytes.com/topic/268286-android-chrome-redirect-not-same-as-others-posted-on-here/

**Comment by srowen** [comment]
No, that is a different app actually. It is undoubtedly a clone of this one, but different icon, etc. It is not this app our source code, which has nothing to do with these malware attacks.

**Comment by Griftaz** [comment]
I don't know what to say. I just reinstalled it from [your link](https://play.google.com/store/apps/details?id=com.google.zxing.client.android) on this github, and the redirection started again. Uninstalled it again, and the redirections stopped.

It's not my job to make you believe me, but those are the facts. I wish you the best of luck figuring out how this happened, and hope that you app's ratings recover from this.

Cheers.

**Comment by srowen** [comment]
Yep, something else is leveraging intents and defaults maliciously to do this stuff. I am not sure how, but it's not this app. I can't update the app anyway unfortunately (it hasn't been updated since Feb 2019 anyway, so, really can't be the app?), so not sure what to do there. Anyone's welcome to examine the source, build from source and install, and probably unfortunately find whatever this is still happens. Many of the links I'm seeing appear to be from another app, with probably the same name or even icon. That may be part of it.

**Comment by saenglert** [comment]
Hi!
Any update on this?

> I can't update the app anyway unfortunately 

How so? Your email is listed as contact even in the play store. So my first guess would be you are the main developer. However, looking at the organization on [github](https://github.com/orgs/zxing/people) there are no public members. So forgive me for asking but who is running the show here and in the play store?

**Comment by srowen** [comment]
I am the only maintainer. But I do not work on this actively. Apps that target API 19 or earlier cannot be uploaded to Play anymore. Rewriting this app to target 20 would be a significant change. 

But, again, nothing about what anyone is talking about here is related to the app or its code. Indeed the app hasn't been changeable in almost 2 years. So not possible this app 'became' malware now.

**Comment by saenglert** [comment]
> Indeed the app hasn't been changeable in almost 2 years.
Looking at the updates yeah I see that. My question is more along the lines of "Any idea who did it"?

> I am the only maintainer. But I do not work on this actively. Apps that target API 19 or earlier cannot be uploaded to Play anymore. Rewriting this app to target 20 would be a significant change.

My Java is quite rusty, and I haven't worked on Android before anyway.  :/

Do you not work on this project anymore because you lost interest or because you simply don't have the time available? In case of the latter the wiki mentions that some vendors bundle it with their firmware. Might be able to make a deal with them to get some funding for an updated version in return? Would be in their interest as well, as it will eventually break.

**Comment by srowen** [comment]
The .apk has not been changed. It really isn't related to this app. Someone has just built their own clone with the OSS code, I'm guessing. 
This has not been my job to work on in 12 years, so yes it's a question of not wanting to work on it while trying to maintain the code when others suggest changes. 
If you update it cleanly, you can open a PR here, or anyone can. Anyone can fork it too I suppose.

**Comment by andrew-tc** [comment]
Just want to update everyone that the offending "Barcode Scanner" app and ZXing's "Barcode Scanner" app, while both sharing the same name, **is a different app**.

We just had a report on [Android Enthusiasts Stack Exchange](https://android.stackexchange.com/q/233322/44325) and based on further investigation, the offending app's package name is `com.qrcodescanner.barcodescanner` that [has been removed from Play Store recently](https://www.appbrain.com/app/barcode-scanner/com.qrcodescanner.barcodescanner). Based on [VirusTotal analysis](https://www.virustotal.com/gui/file/b41f3c76f03eff7a6549829e05f62b68969fc22b2643d282edd8d3c2dc4687b9/detection), the app is using ZXing's source code as a base and added ads on the top of it.

**Comment by srowen** [comment]
Great, thanks for that. I certainly knew this app wasn't malware but good to have 'proof' that it was indeed a clone.
