### ISSUE TITLE
Support action [add repository to F-Droid app]

### ISSUE THREAD

**Issue by kekukui** [zxing/zxing#1368]
Example QR code
https://fluffychat.im/en/fdroid.html

**Comment by srowen** [comment]
Hm, in the past I haven't distributed it anywhere except here and Play, but I can't upload to Play anymore. It'd be reasonable to release there, even unofficially - can third parties upload new versions of the app? otherwise I'd say, well, people can always install the .apk releases after downloading it from Github.

I'd be more inclined if the app were being updated much but it's quite old now and not being maintained, so, may not add much.

**Comment by kekukui** [comment]
> **haven't distributed it anywhere except here and Play**

You did not submit this to F-Droid?
https://f-droid.org/en/packages/com.google.zxing.client.android/

This issue was actually a feature request - the QR code action referenced in the link above was to add an external repository to the F-Droid app on Android (fdroidrepos://).  If zxing is not being maintained, it should probably be removed from the F-Droid repository.

**Comment by srowen** [comment]
No, looks like F-Droid added it. I don't object to it being there but yeah not in my control right now.

**Comment by fossdd** [comment]
The community has it in control. The metadata of your app is here: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.google.zxing.client.android.yml

Do you want that we move it to the archive?

**Comment by srowen** [comment]
No need to remove it or anything, seems like these are of course copies of the real releases.

**Comment by fossdd** [comment]
Okay. F-Droid builds all apps from source. So we have another signature, but the source code is the same.
