### ISSUE TITLE
Parsing a specific Cyrillic code with Zxing gives a wrong result

### ISSUE THREAD

**Issue by Psijic** [zxing/zxing#1374]
#### Description of the problem:

Parsing a specific code with zxing (also checked the same problem with BoofCV) gives a wrong result in the text:
`ST00011|Name=ÎÎÎ "Ãàçïðîì ìåæðåãèîíãàç Âëàäèìèð"|PersonalAcc=40702810710020102692|BankName=������������ ��������� N8611 ÏÀÎ Ñáåðáàíê|BIC=041708602|CorrespAcc=30101810000000000602|PayeeINN=3328415442|KPP=775050001|PersAcc=04067759|LastName=ﾊﾀﾐﾀﾂﾀﾅﾂﾀ|FirstName=ﾅﾋﾅﾍﾀ|MiddleName=ﾍﾈﾊﾎﾋﾀﾅﾂﾍﾀ|PayerAddress=602254, ÌÓÐÎÌ, Ã, ÄÇÅÐÆÈÍÑÊÎÃÎ, ÓË, ä.10, êâ.10|PaymPeriod=0120|Sum=14212`

There are 3 encoding types and one is completely inconvertible: `BankName=������������ ���������
`
While the default Google Vision library gives a result with affordable parameters:
`ST00011|Name=ÎÎÎ "Ãàçïðîì ìåæðåãèîíãàç Âëàäèìèð"|PersonalAcc=40702810710020102692|BankName=Âëàäèìèðñêîå îòäåëåíèå N8611 ÏÀÎ Ñáåðáàíê|BIC=041708602|CorrespAcc=30101810000000000602|PayeeINN=3328415442|KPP=775050001|PersAcc=04067759|LastName=ÊÀÐÀÂÀÅÂÀ|FirstName=ÅËÅÍÀ|MiddleName=ÍÈÊÎËÀÅÂÍÀ|PayerAddress=602254, ÌÓÐÎÌ, Ã, ÄÇÅÐÆÈÍÑÊÎÃÎ, ÓË, ä.10, êâ.10|PaymPeriod=0120|Sum=14212`
This result is also available in web sites like https://decodeit.ru/qr

**Which library version are you using?**
com.journeyapps:zxing-android-embedded:4.1.0
com.google.zxing:core:3.3.0 / 3.4.0

**Which phone/tablet are you using, and which Android version does it run?**

Many Android phones (Samsung Galaxy A71)

**Comment by srowen** [comment]
You need to show the QR code. Often the problem is in the QR code's encoding, or how you display it to a terminal.

**Comment by Psijic** [comment]
> You need to show the QR code. Often the problem is in the QR code's encoding, or how you display it to a terminal.

Sure https://i.imgur.com/643T3sn.jpg

**Comment by srowen** [comment]
I'm not sure what the encoding of BankName is meant to be, but, it has to be specified with an ECI segment to ensure it's read correctly. The BYTE mode segment starting at "|BankName=" doesn't have one, so the encoding has to be guessed. It guesses UTF-8 but it looks like Windows-1251, from your result and the bytes.

Can you put an ECI segment specifying this before the BYTE segment? that's the most correct thing to do. Otherwise it's left to guess and this library won't guess Windows-1251. Or use UTF-8?

One thing I've been meaning to try is to swap in ICU4J for better charset detection: https://unicode-org.github.io/icu/userguide/conversion/detection.html It still won't be perfect but might guess these better than the old heuristics in the code.

But yeah that's technically not quite the correct encoding as a QR code.

**Comment by srowen** [comment]
I tried out ICU4J, and it does a good job! it detects this byte segment as Windows-1251 so the result is as expected. There are only a few problems:

- Its guesses on short strings are often wrong for the QR code context
- I'm hesitant to change detection logic for a really established library
- The ICU4J library is pretty large to include as a dependency for the relatively tiny core library

But I think there's a reasonable solution. In this case, the 'guess' of UTF-8 for the Windows-1251 segment is obviously wrong. It results in unprintable characters. In that case, I think it's reasonable to fall back to ICU4J detection. That wouldn't change any results except in cases like this where the result doesn't make sense.

And, it's possible to mark ICU4J as an optional dependency, so that it still works even if not included, so downstream users don't have to ingest the library unless they want to.

I'll open a PR soon with this idea.

**Comment by Psijic** [comment]
`Can you put an ECI segment specifying this before the BYTE segment? that's the most correct thing to do. Otherwise it's left to guess and this library won't guess Windows-1251. Or use UTF-8?`
Could you explain how to do it with zxing? Because it's not possible to change QR code.

**Comment by srowen** [comment]
I have some interesting results after hacking ICU4J detection into this - it gets some segments right, but not all of them, especially short ones. Before I say more about that -- a quick fix may be to set `DecodeHintType.CHARACTER_SET` to `"Windows-1251"` in your case, if you know that the byte segments are meant to be interpreted that way.

**Comment by srowen** [comment]
The comment about ECI segments means changing the QR code. I'm saying it's not really correctly encoded as-is.

**Comment by Psijic** [comment]
Yes, if all codes are encoded correctly - there is no such problem. Anyway, Google found the method how to recognize them therefore it's possible to include in Zxing.

**Comment by Psijic** [comment]
Yeah, it helps a lot. I set `DecodeHintType.CHARACTER_SET to charset("Windows-1251")` in `DefaultDecoderFactory`.
But curious how Google can find a proper charset if my phone locale is English. Maybe Zxing also will can after your patch?

**Comment by srowen** [comment]
Probably just better encoding guessing than ICU4J. There was better tech there when I was at Google in 2008.

One thing that could work well in a case where all the segments have the same encoding is to combine them before guessing. But there's no guarantee they're all the same. But that change would be significantly more work.

Really it's best to use something standard like UTF-8 with a BOM, if not an ECI segment, when encoding. Otherwise there's no guarantee readers interpret it as expected. For example as I recall some devices used to just assume Shift_JIS in Japan always.

**Comment by Psijic** [comment]
It's not possible to change QR codes encoding methods because these codes don't belong to us.

**Comment by MrChurilov** [comment]
@Psijic Did you fix it(херню)? Or did you use a different solution?

**Comment by Psijic** [comment]
@oehhar my method looks more as an ad-hock for specific purpose but not as a general solution

**Comment by oehhar** [comment]
Sorry, but if it would do more here, it would be a step in the wrong direction. Strictly and only interpreting the data as ISO-Latin1 would be the only valid option. Anything else is wrong. The code should be changed and include the information.
Sorry,
Harald

**Comment by Psijic** [comment]
Maybe AI and neural nets will help us here in the future.
