### ISSUE TITLE
Image no longer decodes

### ISSUE THREAD

**Issue by jkatsiotis** [zxing/zxing#1438]
This is the image: https://i.ibb.co/bPzJbZR/barcode-bug.jpg

While it was decoding on previous versions now it fails to decode.

**Comment by srowen** [comment]
Hm, not sure. It looks like the bars are a little uneven. If you can debug and identify the issue let me know, but I generally don't look at 'single image doesn't decode'

**Comment by micjahn** [comment]
Since the following issue was fixed the decoding fails:
https://github.com/zxing/zxing/issues/909
This was changed from
MAX_INDIVIDUAL_VARIANCE = (int)(PATTERN_MATCH_RESULT_SCALE_FACTOR * 0.78f);
to
MAX_INDIVIDUAL_VARIANCE = (int)(PATTERN_MATCH_RESULT_SCALE_FACTOR * 0.5f);

With a value of 0.6f the decoding works.
MAX_INDIVIDUAL_VARIANCE = (int)(PATTERN_MATCH_RESULT_SCALE_FACTOR * 0.6f);

I'm not sure if this would be a proper fix.

**Comment by srowen** [comment]
That's from a long time ago. It's possible this causes some images to work and others not to; it seemed like a net win. If you an find a small variation on the change that seems to improve overall accuracy, open a pull request. Otherwise that's just how it is

**Comment by jkatsiotis** [comment]
The C++ lib converts it successfully though, so I guess something was corrected there that wasn’t back ported here.

**Comment by axxel** [comment]
The C++ lib (nu-book/zxing-cpp) has been completely rewritten with respect to the 1D barcode code (including ITF) since then. That said, my original proposal to lower the threshold to 0.5 was basically done because I could without sacrificing it's effectiveness with respect to the available samples. Thereby reducing the likelyhood of false positives. I guess your counter example could be reason enough to 'widen' the threshold to 0.6 again. My suggestion: provide a PR and see what @srowen has to say about it :).
