### ISSUE TITLE
Some png files are not being processed correctly

### ISSUE THREAD

**Issue by hauck-jvsh** [zxing/zxing#1541]
We integrate this library in another project (https://github.com/sepinf-inc/IPED/) to detect images with QRCodes, however when processing some images the library consumes more than 4 GB of ram and throws an out of memory exception. This only happens when using the method decodeMultiple from the class QRCodeMultiReader. When using the method decode from the QRCodeReader class the out of memory didn't happen, but it takes an unusual large time to finish. An image that triggers the problem is attached.
![teste](https://user-images.githubusercontent.com/67768441/177412541-335d7320-b1a7-445a-9925-701ad4395340.png)

**Comment by srowen** [comment]
That sounds like a problem with the PNG file or the library that reads it; this library does not read images itself.
Can you supply an example? otherwise, no way to help.

**Comment by hauck-jvsh** [comment]
I don't think so, as the thread dump is locked inside the library, and the image is read using the following code
`BufferedImage img = ImageIO.read(in);
 BinaryBitmap binaryBitmap = new BinaryBitmap(new HybridBinarizer(new BufferedImageLuminanceSource(img)));
 QRCodeMultiReader reader = new QRCodeMultiReader();
 Result[] results = reader.decodeMultiple(binaryBitmap);
`

> at com.google.zxing.common.PerspectiveTransform.transformPoints(PerspectiveTransform.java:77)
> 	at com.google.zxing.common.DefaultGridSampler.sampleGrid(DefaultGridSampler.java:63)
> 	at com.google.zxing.qrcode.detector.Detector.sampleGrid(Detector.java:191)
> 	at com.google.zxing.qrcode.detector.Detector.processFinderPatternInfo(Detector.java:133)
> 	at com.google.zxing.multi.qrcode.detector.MultiDetector.detectMulti(MultiDetector.java:61)
> 	at com.google.zxing.multi.qrcode.QRCodeMultiReader.decodeMultiple(QRCodeMultiReader.java:61)
> 	at iped.engine.task.QRCodeTask.process(QRCodeTask.java:144)

**Comment by srowen** [comment]
I don't think so; that part of the code does not allocate memory. Still need more info, like an example file. Or your heap dump stats. This can't be an allocation site.

**Comment by srowen** [comment]
It could be that the uploaded image is very large, which would put memory under pressure.
Are you trying to say that this is the site that is _running a long time_? that makes sense if the image is huge. But then the problem is the input, which is again why a sample is necessary.

**Comment by hauck-jvsh** [comment]
What kind of file do you need? the heap dump I can attach.

**Comment by srowen** [comment]
The image file!

**Comment by axxel** [comment]
@srowen what about the one he provided [here](https://github.com/zxing/zxing/issues/1541#issue-1294746299)? ;)

**Comment by hauck-jvsh** [comment]
The image is attachted
[test.zip](https://github.com/zxing/zxing/files/9049672/test.zip)

**Comment by hauck-jvsh** [comment]
The thread dump is big, 2GB if compressed with 7z it stills 606MB.

**Comment by srowen** [comment]
Oh I totally ignored that, it's not a barcode? surely this isn't what you're feeding to the library. But, sure, that's a huge image with no barcode in it. It's going to take a long time to search for barcodes of all types all over it anyway. I am not sure that's unexpected?

**Comment by axxel** [comment]
No offense, but in 2022 a 1080p image can hardly be considered 'huge', can it? And of all images ever fed to your library, I'm pretty sure only a small portion did actually contain a barcode (thinking about video input on phones).

This input runs through [nu-book/zxing-cpp](https://github.com/nu-book/zxing-cpp) in a few ms with a trivial amount of memory used. This clearly sounds like a bug in the `QRCodeMultiReader`, based on the above description.

**Comment by lfcnassif** [comment]
Firstly, thank you for this great library! The original issue that originated this is: https://github.com/sepinf-inc/IPED/issues/1203

Analyzing the heap dump, it is possible to see some classes of zxing taking about ~24GB of RAM when the OOME was thrown, when processing multiple files at the same time.

Files that triggered the issue are from an user and has sensitive info, he kindly sent the generated heap dump to me. @hauck-jvsh cleaned up one of the triggering files, removing sensitive info, and attached it here zipped above.

**Comment by lfcnassif** [comment]
As noticed by @hauck-jvsh, possibly the image background is generating many many qrcode candidate combinations, taking a long time to evaluate and consuming lots of memory resources.

Maybe a possible solution would be to have some config into the library to the maximum number of qrcode candidates to evaluate?

**Comment by hauck-jvsh** [comment]
I just forget to say that we are setting the decode hint DecodeHintType.TRY_HARDER to true.
The actual decodeMultiple line is 
` reader.decodeMultiple(binaryBitmap,Collections.singletonMap(DecodeHintType.TRY_HARDER, Boolean.TRUE));`

**Comment by lfcnassif** [comment]
> Oh I totally ignored that, it's not a barcode? surely this isn't what you're feeding to the library. But, sure, that's a huge image with no barcode in it. It's going to take a long time to search for barcodes of all types all over it anyway. I am not sure that's unexpected?

Our project processes thousands-millions of files and runs a number of tasks over them. One of the tasks is barcode detection. Reading the library documentation, when no barcode is found, an exception is thrown. Long time to process we can handle with some timeout control, but OOME processing a 190KB file with a heap of GBs, crashing the whole application, I think that is not expected.

**Comment by srowen** [comment]
Well, huge relative to what? normal input to the library, certainly. The library handles this image fine as far as I can tell -- does take a long time to run if asking for all formats, etc. But fits fine in a few hundred MB of RAM. Remember, the images that take the longest are the ones with no barcode in them, as you have to exhaust all the requested possibilities.

Also: .png is compressed. A small .png file in bytes could be very large in pixels, and that's what matters.

I would not be surprised if there's some pathological case here, but, the library itself doesn't allocate much memory beyond what's needed for the image representation. Doing a whole lot of that with huge images in parallel could definitely run  you out of mem or be slow, so I'm still trying to tease apart "slow" from "unreasonably and unexpectedly slow".

I don't think it's the image itself, but the processing. Can you share anything from the heap dump that suggests where the allocation takes place? it can't be the site above. Are you sure it's not other stuff in your app? I'd have to load up a profiler on my end which I can do, just would take some time to set up.

**Comment by lfcnassif** [comment]
> Can you share anything from the heap dump that suggests where the allocation takes place?

I'll try to generate the heap dump, upload somewhere and post the link here.

> it can't be the site above

The triggering file is exactly the image @hauck-jvsh posted here, the site it is showing up is just occasional. I think libraries should be prepared to any kind of input, you can't control what users will provide to it. This can be considered a security DOS CVE because it can take services using this library down...

> Are you sure it's not other stuff in your app?

We are pretty sure, give me some time...

**Comment by srowen** [comment]
I disagree - you can make the best code run arbitrarily slow with enough input. That's why I'm trying to distinguish between a simple "I'd like this to use less memory / be faster" from "this is unreasonably slow in comparison to X which ought to be similar". The former is not a bug, the latter is.

You're turning on a large amount of extra processing - try-harder, and scanning for lots of QR codes. This is about the worst case too. Your app can/should defend against input like this other ways, like limiting thread runtime.

I do not work on this project anymore, so it's pretty much WYSIWYG; that's why I'm asking for more specifics and ideally a patch.

That said if I can get the profiler up and running again I'll take a look.

**Comment by lfcnassif** [comment]
@srowen I really appreciate your attention, thank you very much. As an open source developer, I know users/devs usually don't appreciate personal time dedicated to open source projects like this.

Below is a testing code that triggers the OOME with -Xmx5G (I didn't test with higher values) on the PNG file @hauck-jvsh shared above using java 11:
```
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.Collections;

import javax.imageio.ImageIO;

import com.google.zxing.BinaryBitmap;
import com.google.zxing.DecodeHintType;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import com.google.zxing.multi.qrcode.QRCodeMultiReader;

public class Test {

    public static void main(String[] args) {

        try {
            File testFile = new File("E:\\test.png");
            BufferedImage img = ImageIO.read(testFile);
            BinaryBitmap binaryBitmap = new BinaryBitmap(new HybridBinarizer(new BufferedImageLuminanceSource(img)));
            QRCodeMultiReader reader = new QRCodeMultiReader();
            Result[] results = reader.decodeMultiple(binaryBitmap,
                    Collections.singletonMap(DecodeHintType.TRY_HARDER, Boolean.TRUE));

        } catch (Throwable e) {
            e.printStackTrace();
        }
    }
}
```
This is the heap usage chart from jvisualvm:
![image](https://user-images.githubusercontent.com/7276994/177427644-568e622d-a2dd-46d2-98e8-60da5e1ac2dd.png)

And this is the generated heap dump:
https://pfgovbr-my.sharepoint.com/:u:/g/personal/nassif_lfcn_pf_gov_br/EcJmmD6BdllCokk8PzUScaMBp23QpieiL9tjD4QImCfDjA?e=XydPuM

**Comment by srowen** [comment]
Yeah I see something similar in a profiler - it's creating a whole lot of objects for sure, though they seem to be garbage-collectable. Still that can cause OOM if the JVM is under enough memory pressure.

It seemed like a lot more than made sense, and on digging in, I see things like: this image turns up 1217 candidate finder pattern points, from which it compares all triplets to find a possible code - it is O(n^3) in the number of candidates. 1217 seemed like far too many to _confirm_ and indeed on looking at the code, I think this section misses one key check - only consider finder patterns that have at least 2 'votes'. That vastly cuts down the size of the work, and thus memory.

That I do think is just a bug, not merely running slowly on big input (though this kind of big non-barcode input triggers the problem most easily), and yes I think that is a problem, as it spends thousands of times too long evaluating possibilities, and there are infinitely many normal images that would cause this issue.

I can make a quick fix and if you like, you can build and test an updated .jar to confirm.
I don't have many good tests for this functionality, so am not 100% sure of the effect of the change, though, don't think it's reasonable to do otherwise.

Thank you for the report, this is a good catch and wasn't hard to find once I had something to look at.

Do you really need the 'multiple' QR code detector? avoiding that avoids this issue as well. In case that's a faster fix for you.

**Comment by srowen** [comment]
https://github.com/zxing/zxing/commit/78c2a9c4401e166be22ba1483cc1c7d090bdf8b8

**Comment by lfcnassif** [comment]
Awesome, thank you @srowen for digging into this so fast! For sure, we will test your fix tomorrow with other similar triggering files. We already switched to single QR code detector to avoid this, but we probably will rollback the change when a fixed release is out.

**Comment by lfcnassif** [comment]
I couldn't wait :-). The fix worked on other 5 similar triggering files, thanks! I'll run on a large test set through the night to check for regressions on detection.

**Comment by hauck-jvsh** [comment]
Wow, that was fast, thank you, tomorrow we will test this in some large datasets of images.

**Comment by srowen** [comment]
I think that's inevitable, as it now refuses to consider weakly detected points. Maybe I can tweak the logic a little to catch edge cases, not sure.

**Comment by lfcnassif** [comment]
Thank you @srowen, don't worry, I just reported for a possible future improvement, I think it's better with the fix than without it.
