### ISSUE TITLE
Why scanning bar codes  slow？

### ISSUE THREAD

**Issue by Ryan44real** [zxing/zxing#1817]
First, thanks for this great library. It responds quickly when recognizing QR codes, but very slowly when scanning barcodes, how can this be solved?

**Comment by oehhar** [comment]
Perhaps I can say, that QR-Code (Abreviation for "Quick Response Code") was exactly designed for that: quick reading (of direct part markt metall parts in automotive applications).

The time to read is to find the code. QR-Code solves this task by having three small finder pattern detectable by a linear line signal allocated in a larger form (L shape). This is just quick.

With bar-codes, you try to detect the bars, turn them to get them horizontally, sum the bars and decode the bar width. In addition, often it is hard for camera optics, as long shapes are not easy.

I write this without knowing how zxing works internally...

Take care,
Harald

**Comment by axxel** [comment]
If you care for speed, you might want to have a look at https://github.com/zxing-cpp/zxing-cpp. There is also an Android wrapper (among others) available. The demo app allows to switch live between this Java project and the c++ port. The latter is around 8x faster than the former on my Pixel 5 when `tryHarder` is enabled.

The main reason why this particular implementation is relatively slow for the linear symbologies is because the rather expensive operation of doing basically a run-length encoding is repeated for each linear symbology instead of once for all of them, which is a huge waste of cpu cycles.

**Comment by srowen** [comment]
I think the more direct answer is - some 1D formats are harder to read. Harder means slower, as it means more frames have to be analyzed before it's succesful. However, looking for and decoding a 1D code is actually faster than a QR code, per frame

**Comment by Ryan44real** [comment]
Thanks all guys, the form of the barcode makes it slow to be recognized by the camera, thanks for the answers!
