### ISSUE TITLE
Allow sharing in multiple formats.

### ISSUE THREAD

**Issue by t-8ch** [zxing/zxing#201]
It would be nice to be able to share data in all encodings supported by zxing.
There could be a dropdown menu in the title bar of the share view, where a format can be selected.

Usecase:
I got a notification about a package pickup by (classic) mail with a ITF code and a email about this notification.
As the package pickup station only accepts ITF codes, I could have phoned my flatmate to send me the plain number printed beneath the ITF code and generate a new code from it.

**Comment by LenaicTerrier** [comment]
I think this would be a great feature, allowing users to store strings instead of images files for coupons, cinema tickets, parcels and miscellaneous orders.
I don't know the situation in other countries but in France, this would be helpful since companies don't use only QRCode for this kind of things.

Regards.
