### ISSUE TITLE
qrcode margin increases when content increases and eventually the qrcode shrinks in size.

### ISSUE THREAD

**Issue by adityashedge** [zxing/zxing#257]
This is a weird issue. When the content for vCard increases, the margin around qrcode increases.
In my code I am setting 'MARGIN' to 0 in 'com.google.zxing.EncodeHintType' and this is how I want it.
But what I noticed was that if the name name is long, then the qrcode strinks in size. I need the qrcode to be of 300 x 300 size. 

I am generating these qrcode using MRI ruby 2.1.1 with zxing/core jar in a Rails(v 4.1.0) web app.
ATM i am using an older version(not sure which version) but I have tried with version 3.1.0 and I am getting the same result.

Below are some sample I have generated with my code and older version of core jar. Notice the 3rd qrcode is smaller even though all images are of  same size.
Does anyone know a fix to this issue. Please help me out here.

![q1](https://cloud.githubusercontent.com/assets/4658665/5164891/1c860988-7403-11e4-8782-5986de694444.png)
![q2](https://cloud.githubusercontent.com/assets/4658665/5164892/1ea39244-7403-11e4-9cfc-86bb3d0b4602.png)
![q3](https://cloud.githubusercontent.com/assets/4658665/5164893/220b570a-7403-11e4-8c12-38b185e20056.png)
![q4](https://cloud.githubusercontent.com/assets/4658665/5164895/24bc45f4-7403-11e4-8ff0-a9ae9a5f1f18.png)

**Comment by marcolopes** [comment]
so, how do we avoid the EXTRA white space around? Is there a way to tell the ENCODER the MINIMUM size, and let it "scale" to the next OPTIMUM size? Or do we always have to take into account the CONTENTS and define a based on that? I thought the QRCODE used all the available space with more or less information, and not discarding usable space because it cannot FIT more "modules" :\

Is ZXING encoding QRCODE according to specs? I see this online encoder that uses ZXING having the same behavior: http://zxing.appspot.com/generator/

But this one DOES not!!! Every QRCode i generate uses ALL available space!! https://qrcode.tec-it.com/en

NOTE: 2 QRCODES with the same CONTENT and ERROR CORRECTION should not be exactly equal in therms of image? I'm getting several different results using online oncoders
