### ISSUE TITLE
DataMatrix decoder do not support unicode text

### ISSUE THREAD

**Issue by msva** [zxing/zxing#287]
Hi there!
I've discovered, that zxing (a least, android barcode scanner) decodes DataMatrix codes with unicode text as ASCII (and, so brake it). I.e. it displays `ÑÐµÑÑ` instead of `тест` (ciryllic "test").

OTOH, QR-encoded unicode is decoded fine.

Can somebody fix that (or, at least, advice/guide me how to fix it)?

**Comment by srowen** [comment]
90% of the time people report this it is because the barcode is incorrect. Is it UTF 8 encoded or has an ECI segment? Are you sure it is not your console? Until there is info like a barcode I couldn't say.

**Comment by msva** [comment]
ok, some additional info:
1) it is UTF-8 barcode (generated by libdmtx. And it decodes fine as unicode by libdmtx too). Although it, exactly, maybe something with libdmtx encryption algo (I'd be glad to test generation with zxing itself to be sure, but neither test app nor scanner can **generate** DMTX) ;)
2) I'm sure it is not my console.
3) There is "тест" message: 
![dmtx_test](https://cloud.githubusercontent.com/assets/268102/5746911/707d936a-9c55-11e4-80f6-85b7cab1a4dd.png)

4) can you describe, how to check for ECI segment, please? Then I'd be able to answer this question too....

**Comment by msva** [comment]
is it any more info that I can provide?

**Comment by srowen** [comment]
The barcode encodes 6 bytes with Base 256 encoding, and that is the entire content of the barcode. Without an ECI segment, the spec says that the bytes are interpreted as ISO-8859-1, so the result from the library is correct. The barcode needs an ECI segment.

Now, I also don't know that ECI support was ever finished for Data Matrix. But that wouldn't be hard to tack on since it's implemented for QR code. But this barcode does not have one.

**Comment by msva** [comment]
btw, I've another dmtx-barcode with same encoded text. And, as far as I understand, it has mark of extended ascii (and generated by another app). And, to be honest, I have absolutelly no idea, how should look like **proper** ECI mark "there is UTF-8 inside" (I bet, it is not enough to just have \x241 as first byte in codewords. Advice me, please, how does it marked for QRs?

**Comment by srowen** [comment]
Yeah do you have the spec? codeword 241 introduces an ECI segment. The encoding should be the same as in QR codes. These aren't described in the spec but you can see how it is implemented in QR codes. It should just be followed by a single 8-bit value for the character set. UTF8 is 26.

**Comment by eladts** [comment]
Is there an online encoder that uses ECI and works correctly with the zxing decoder? I tried https://www.free-barcode-generator.net/datamatrix/ and it doesn't work correctly, but for QR https://www.free-barcode-generator.net/qr-code/ does work with both UTF-8 and ISO-8859-8.

**Comment by eladts** [comment]
The zxing decoder does **not** support ECI with Data Matrix, as evident by the code:

`         case 241: // ECI Character
            // TODO(bbrown): I think we need to support ECI
            //throw ReaderException.getInstance();
            // Ignore this symbol for now
 `

at zxing/core/src/main/java/com/google/zxing/datamatrix/decoder/DecodedBitStreamParser.java

The OP is correct and the issue should be reopened. As zxing does support ECI and auto UTF-8 detection for QR, it should be simple to add these capabilities to the Data Matrix decoder,

**Comment by srowen** [comment]
Ah, this isn't implemented in DM. Yeah it should be.

**Comment by pschichtel** [comment]
I'll might work on it this evening

**Comment by gredler** [comment]
If it's helpful, Okapi has a couple of ECI DM symbol test images here (eci-chinese and eci-japanese):

https://github.com/woo-j/OkapiBarcode/tree/master/src/test/resources/uk/org/okapibarcode/backend/datamatrix

The PNG files have corresponding .properties files which have more information about what is encoded in each image.

**Comment by pschichtel** [comment]
I worked around the issue in my application as the proper solution seems too involved given the current state of the code. I just converted the Result.text back to bytes and did my own simple charset detection based on BOMs.

**Comment by MortenBork** [comment]
Code piece from the zxing encoder -> the msg.getBytes() -> I hard coded to ONLY use ISO-8859-1. 

Code below:

EncoderContext(String msg) {
    //From this point on Strings are not Unicode anymore!
    byte[] msgBinary = msg.getBytes(StandardCharsets.ISO_8859_1);
    StringBuilder sb = new StringBuilder(msgBinary.length);
    for (int i = 0, c = msgBinary.length; i < c; i++) {
      char ch = (char) (msgBinary[i] & 0xff);
      if (ch == '?' && msg.charAt(i) != '?') {
        throw new IllegalArgumentException("Message contains characters outside ISO-8859-1 encoding.");
      }
      sb.append(ch);
    }
    this.msg = sb.toString(); //Not Unicode here!
    shape = SymbolShapeHint.FORCE_NONE;
    this.codewords = new StringBuilder(msg.length());
    newEncoding = -1;
  }
  
  This is what is causing the data-matrix encoding of a barcode to go nuts, if you attempt to store letters like "ć" or "Ŕ"
  
  You are just completely boned. 
  
  The only thing you can do, is wipe all none ISO-8859 characters from your strings, and then have them missing from the DataMatrix barcode. 
  
  You cannot compose in a different encoding etc. 
  
  Now, this might be a constraint required by the Datamatrix reader devices, that these are only allowed to understand this ISO-8859-1 encoding, but then whomever made that choice is an idiot. 
  
  Anyway, you can't. This is the short, real, answer here. The data-matrix format REQUIRES ISO-8859-1 compliance on using strings for forming the barcode.

**Comment by terryburton** [comment]
> Now, this might be a constraint required by the Datamatrix reader devices, that these are only allowed to understand this ISO-8859-1 encoding, but then whomever made that choice is an idiot.

@MortenBork I respectfully suggest that you are speaking from a position of ignorance. You may find it useful to educate yourself on ECI protocol which is intended to resolve this issue. Here's a start: https://www.linkedin.com/pulse/enhanced-channel-interpretation-terry-burton/

In the absence of ECI a barcode is simply a bag of bytes defined to be interpreted as Latin-1. The design for Data Matrix predates standardisation of Unicode so this most commonly used encoding at that time what selected.

ECI is an extension to the reader to host transfer protocol that is in part akin to a HTML meta charset tag, allowing the bytes carried by a symbol to have an alternate interpretation by the receiving application, e.g. UTF-8.

> Anyway, you can't. This is the short, real, answer here. The data-matrix format REQUIRES ISO-8859-1 compliance on using strings for forming the barcode.

This is not true. ECI has been part of every 2D symbology standard since PDF417. However it is certainly true that for practical purposes you may struggle to use ECI effectively in open systems due to implementation concerns, not deficiencies in the symbology standards.

Unfortunately support for encoding ECI indicators within barcode symbols has historically been lacking from barcode generators, however there has been recent efforts to improve support for ECI in Open Source encoders and decoders. ECI is also having a renewed focus within the standards bodies at this time which should drive improvements in the proprietary decoder space.

**Comment by srowen** [comment]
I'm pretty sure ECI segments are part of the DataMatrix spec, indeed, and this is exactly why they're there. I haven't looked at the impl here in a long time, but if ECI isn't supported in DataMatrix it should be, it's valid.

**Comment by oehhar** [comment]
+1 on support ECI. as Symbology IDs are now supported (requirement for ECI), the next step toward unicode may be done.
Thanks to the team, great !
Best regards,
Harald

**Comment by MortenBork** [comment]
Let me first start by apologizing for the harsh tone in the previous statement. Too much Reddit.
I really need to work on that. 

 How my point stands, unless you (the coder) is willing to implement the ECI standard into the zxing component used to handle the encoding of the bytes used for building the symbols for the Data-Matrix 2D barcode -> You are out of options. 
 
 And I have looked around, an quite large sample set actually uses the zxing component as a dependency on their own components that render this particular barcode. 
 
 The top 3 suggestions on bealdungs website does. 
 
 I actually haven't been able to find one, and would humbly accept anyones knowledge of a component that allows the usage of utf-8 strings in the generation of a data-matrix 2d bar-code? 
 
But I don't think that this would technically work -> the readers using the ECI channels would also need to be able to handle the outputted characters, if you have a hard limit on the encoding used, all readers would also need that update to them, or the "legal" character set used, will just render nonsense. 

Plus the reader would need to know WHICH ECI channel was used to render the characters in the string. 

This effectively means: 

You, as an individual, cannot, push none-ISO-8859-1 characters into a data-matrix 2D barcode. 

Because the work-around might not be available everywhere. Your current setup would likely need an extensive deployment to allow for the extra property, on both the producer and the consumer side of the data. 

So to answer OP's original question. You can't, as a single person, do anything about this. This requires a restructure, and a significant one, if your system, and the intended recipients systems.

**Comment by oehhar** [comment]
There are unfortunately no coders, sorry. The project is in maintenance mode and only until an individual (like you) implements something, nothing can be done. Thats why I was very happy that an individual (payed by REA by the way) has implemented AIM Symbology IDs.

I can only say to you that ECI is the way to go.

Sorry and my compassion,
Harald

**Comment by greennetwork** [comment]
**If you want to scan codes more easily with your camera
Recommended Scanning Kit
Service Introduction**

[Scan Kit scans, parses, and generates major 1D and 2D barcodes, helping you quickly build barcode scanning functions into your apps.Scan Kit automatically detects, magnifies, and recognizes barcodes from a distance, and is also able to scan a very small barcode in the same way. It works even in suboptimal situations, such as in dim light condition or when the barcode is reflective, dirty, blurry, or printed on a cylindrical surface. This leads to a high scanning success rate, and an improved user experience.Scan Kit can be integrated into both Android and iOS apps. Android apps with Scan Kit integrated support barcode scanning in landscape mode.](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/service-introduction-0000001050041994)

**Comment by msva** [comment]
@pschichtel did you had any success in zxing-side fix of that issue?

**Comment by pschichtel** [comment]
@msva I worked around the issue by doing some simple encoding detection and reencoding it

**Comment by srowen** [comment]
Should be largely resolved by https://github.com/zxing/zxing/pull/1474
