### ISSUE TITLE
Use front camera

### ISSUE THREAD

**Issue by harish118** [zxing/zxing#288]
hi,

The barcode scanner uses the back camera on my android phone. Is there a way to default / switch to the front camera automatically on startup?

Thanks a ton,
M&M

**Comment by srowen** [comment]
Hm, no since in general that is not a good camera for scanning. It will choose the front camera if it is the only camera. It can also be selected when opening the app by Intent, since in some cases the calling app knows for sure that it wants only the front camera.

There's an option for it in the for-pay "plus" app: https://play.google.com/store/apps/details?id=com.srowen.bs.android

I hadn't planned to do more back-porting from it, but if someone opened a decent PR to add this functionality I'd merge the best of both implementations.
