### ISSUE TITLE
using initiateScan() in android.support.v4.app.Fragment is not invoking onActivityResult()

### ISSUE THREAD

**Issue by drindt** [zxing/zxing#291]
I tried the following inside the android.support.v4.app.Fragment:
```java
 IntentIntegrator integrator = new IntentIntegrator(getActivity());
```
The constructor for the Fragment is only available for the native Fragment provided by the SDK in the device not the support-v4 or package.
After deeper investigation i find out that the REQUEST_CODE:
https://github.com/zxing/zxing/blob/6c522f127a0ac40b2e14518528c9547018e044b2/android-integration/src/main/java/com/google/zxing/integration/android/IntentIntegrator.java#L112

value seems the issue. It prevents later in the FragmentActivity here:
http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/5.0.0_r1/android/support/v4/app/FragmentActivity.java/#150
that the index is not 0. Then it traverses through all fragments and invokes onActivityResult() properly.
I set a breakpoint with the debugger and modified the REQUEST_CODE and it works. I haven't tested it if this implies other problems.

Would be nice to have your feedback. Thank you very much for reading.

**Comment by drindt** [comment]
Further testing brings this as a temporary working solution:
```java
IntentIntegrator integrator = new IntentIntegrator(getActivity()) {
    @Override
    protected void startActivityForResult(Intent intent, int code) {
        EditorFragment.this.startActivityForResult(intent, 312); // REQUEST_CODE override
    }
};
```

**Comment by srowen** [comment]
I don't know much about Fragments. What's the problem here though? As I understand the top 16 bits are not used by the app. The request code `0xc0de` and 312 have all 0s in top bits, both. Are you saying a different request code needs to be used? This just seems to try to change which fragment gets the call to `startActivityForResult` but isn't that controlled by passing it into the `IntentIntegrator` constructor?

**Comment by drindt** [comment]
I don't understand the thing with the "top bits". I think there is another request code required in the constant. I would recommend to remove the Constructor `IntentIntegrator(Fragment fragment)`. If you invoke the Integrator inside a Fragment you can use `getActivity()`. This releases also the dependency to the `Fragment` class. Also the used `Fragment` class is the native Fragment. Google recommends and i guess a lot uses the `Fragment` from the support package. So further code which handles if its an `Fragment` can removed. `FragmentActivity` takes care about the delivery via `onActivityResult`.
If my english is to bad to understand i can create a diff to better visualize this.

**Comment by srowen** [comment]
I suppose I'm asking whether the "312" is the necessary change, or calling `startActivity` on the `Fragment`? I would not expect that the value matters as long as its top 16 bits are 0 (these are reserved from Android 3.x onward IIRC). I also expect that you can use the constructor for `Fragment` if you need its method invoked. Do we need a different, other constructor?

**Comment by drindt** [comment]
The "312" i just tried out as a replacement and it works. With the original `REQUEST_CODE` i had no success. Tested both starting from activity and fragment with my adjustments with positive results.

I have pushed my fix here for your review:
https://github.com/Viselabs/zxing/commit/69d0ee41c727cf1682029de48218e6567f46ad14
I removed unnecessary fragment stuff. Also added conditional flag setting on newer platforms above Lollipop. Not very atomic sorry.

**Comment by rolleric44** [comment]
hi their,  rt? the road O~kay „√ pulling a little filing game with you to
much to get something done and figured O~ut . oOo i seen more often O
sounding like it wants to not bee in the dream teams written work on.
(butt~ons)  I just saw zero ... and lot of extra ... files.. I'd. say..
nuts ... I respect your attention to it.. during the corse I lost alot of
files / does or because it might be legit,  utterly 0 be a stocker crazy
devices rit.?

**Comment by jiggo** [comment]
Hi,
I don't know if it's right to comment here, but the issue I got is somewhat related to this.

I have a fragment (let's say it A) which has 2 nested fragments (let's say them A1 and A2) with a FragmentPagerAdapter. From A1 I want to start the scanner and therefore I'll do this way

```
IntentIntegrator integrator = new IntentIntegrator(getActivity());
integrator.addExtra("SCAN_MODE", "DATA_MATRIX_MODE");
integrator.initiateScan();
```

The I intercept ` onActivityResult(int requestCode, int resultCode, Intent data) ` in the hosting activity and call the relative method on the right fragment
```
 @Override
  protected void onActivityResult(int requestCode, int resultCode, Intent data) {
     if(requestCode == IntentIntegrator.REQUEST_CODE) {
         FragmentManager mgr = getSupportFragmentManager();
         parent = mgr.findFragmentByTag(FRAGMENT_A.TAG);         
         if(parent != null) {
                mgr = parent.getChildFragmentManager();
                // I want the first child because I know he called the scanner
                fragment = mgr.getFragments().get(0);
                if(fragment != null)
                    fragment.onActivityResult(requestCode, resultCode, data);
            }
        }
  }
```
When intercepting ` onActivityResult(int requestCode, int resultCode, Intent data) ` in the hosting activity the `requestCode``` is different from ```IntentIntegrator.REQUEST_CODE`.

Then, I tried to fix this by setting my request code removing `final` from `REQUEST_CODE` and implement a setter called just before the `initiateScan()` method. Snippet:

``` 
integrator.setREQUEST_CODE(FragmentA1.REQUEST_CODE_SCAN_DATA_MATRIX);
```
In this way I have the right code on `onActivityResult` BUT inspecting `mgr = parent.getChildFragmentManager();` it has no childs (!?).

Next step was to use the constructor with the fragment so i did this change (changing the import from android.app.Fragment to android.support.v4.app.Fragment because of Fragment A1)

```
IntentIntegrator integrator = new IntentIntegrator(getActivity());
```
to
```
IntentIntegrator integrator = new IntentIntegrator(this); //this is Fragment A1
```

and now `mgr = parent.getChildFragmentManager();` has the childs but requestCode is again different (although using my setter method).

**Comment by drindt** [comment]
@jiggo Do you have tried my approach from second comment above?

**Comment by Nutomic** [comment]
The problem is that there is no constructor for `IntentIntegrator` that takes `android.support.v4.preference.PreferenceFragment`. Could you implement such a constructor?

The code in the second comment should work, but I'd rather not use that ugly hack.

**Comment by axd1967** [comment]
It's strange that the requestCode is produced by the library. 

Normally it should be the client code that should supply a request code, so that it can switch on it once the scan calls `OnActivityResult`.

Instead, the approach chosen here is to inspect the request via `IntentIntegrator.parseActivityResult()`, which poses at least two issues:

1/ this is needless processing which can be avoided by switching on a client produce request code
2/ there is a potential for request code conflicts - now, an app must make sure to never user a request code that might be in use by the ZXing library.

solution: the client side must add a request code in the `IntentIntegrator()` constructor.

**Comment by srowen** [comment]
Yes there's a potential for conflict, though remote. The cost of the switch is trivial. I don't agree it's better to force the client to provide a code, but, it's also no big deal to add an overload that accepts a request code when the request is made and when it's handled.

**Comment by axd1967** [comment]
IMHO your arguments are weak.

I'm sorry I have to get personal here, but it is my impression that the Android aspect is badly represented in this project.  It now feels that the code was written by someone who knows enough about Java but not enough about Android: e.g. imposing the request code, suggesting a non-standard way to handle the return code, not dealing with the Support Library, not accepting significant merge requests, and the very actual fact that yet another Android dev (me) is hitting this issue.

What is needed is someone with good Android experience to manage the Android part of ZXing, but I understand that someone needs to take the challenge (so please don't take this as negative critic).

I created a small project that demonstrates that the integrator component does not work as advertised, and needs to be rewritten: https://github.com/axd1967/test_qr_zxing .

**Comment by axd1967** [comment]
... and just after writing this, I hit this OMG: 

https://github.com/axd1967/test_qr_zxing/commit/ec44b051388c230c510d5f31a412a927135386fc

I think this is yet another argument that request code handling is wrong, because there is no reason to retransmit the request code back to `IntentIntegrator.parseActivityResult()`.

**Comment by axd1967** [comment]
by the way: in my projects I tend to avoid the wiki.

why? because the content depends on code evolutions, so the content should be some Markdown (or other format) page inside the repository, that is adapted whenever code changes.

(the IMO only advantage of the wiki is the simplified diff tool... it should be implemented everywhere, not only on wiki pages.)
