### ISSUE TITLE
URL truncated after vertical bar ("|")

### ISSUE THREAD

**Issue by dbolton** [zxing/zxing#307]
Steps to reproduce:
1. Scan a QR code for a URL containing a vertical bar ("|"). For example, see image attached
![qr with vertical bar url](https://cloud.githubusercontent.com/assets/712270/6090947/9d992b52-ae57-11e4-81d1-44740ad324d5.png)
2. Tap on the URL to visit the page

Expected behavior: 
You should be able to visit the full web address (which includes a vertical bar): http://www.cofchrist.org/events?tags=organ-recital|dome-and-spire

Actual behavior: 
The URL is cut short at the vertical bar ("|") and it takes you to http://www.cofchrist.org/events?tags=organ-recital instead.

**Comment by srowen** [comment]
No, this decodes correctly to the URL you mentioned. See http://zxing.org/w/decode?u=https%3A%2F%2Fcloud.githubusercontent.com%2Fassets%2F712270%2F6090947%2F9d992b52-ae57-11e4-81d1-44740ad324d5.png

Something else must be going wrong. I bet you are clicking the linkified text link that Android presents instead of Open in Browser? How Anrdoid linkifies text is up to Android, and may stop at |

I am not sure, however, that | is valid in a URL (unescaped). I don't know, I don't have the spec, but http://stackoverflow.com/questions/1547899/which-characters-make-a-url-invalid says it's considered "unwise" to use. Therefore you can simply escape it and probably avoid any issues like this.
