### ISSUE TITLE
QR code reading problem (Android)

### ISSUE THREAD

**Issue by RexpecT** [zxing/zxing#315]
I am trying to read this QR code with the latest Zxing Barcode Scanner, without any success(I was trying with several phones).

![nevtelen](https://cloud.githubusercontent.com/assets/3351437/6283337/54a78786-b8e3-11e4-9098-ddc6097b7257.jpg)

The latest QR Droid app reads immediately.
What is the problem?

Thanks!

**Comment by srowen** [comment]
Hm, not sure. It gets detected exactly right but then the second data block fails error correction. How did you encode it?

**Comment by RexpecT** [comment]
What do you exactly mean by "How did you encode it?" ?

The QR payload is alphanumeric, it is a URL and the part of the URL is RSA encrypted.

The QR spec:
Simbol version (size): (9) 53 x 53;
Error corr.: L (7%);

**Comment by srowen** [comment]
I mean, what encoder did you use? the decoder 'claims' the error correction is wrong. Although it's not impossible there's a bug in the EC routine, it's pretty battle-tested and unit tested now.

**Comment by RexpecT** [comment]
Thanks for your fast reply.
I will write it to you as soon as possible, currently i am waiting for our partner response.

**Comment by wfred101** [comment]
I have verified this QR-Code. The image shows the sequence of Codewords. 
![zxing](https://cloud.githubusercontent.com/assets/6117525/6543010/0965deec-c50b-11e4-9501-8aaf82d9f0ab.png)

It looks normal. Maybe the sequence of Codewords shown in the image helps

**Comment by srowen** [comment]
The problem is that it fails error correction, and I'm trying to figure out whether the encoding or decoder is wrong.

**Comment by wfred101** [comment]
The verifier did not report a fail in the error correction. This looks
then very much like a decoder problem and not a encoding failure.
Attached is the full report. Ignore the ScanLink section. Thats nonsens.

Am 08.03.2015 um 14:42 schrieb Sean Owen:

**Comment by srowen** [comment]
I'm not working on this project anymore, though I can help a bit with merging fixes. Someone would have to pinpoint the decoder problem if there is one and propose a fix.

**Comment by woo-j** [comment]
I have investigated this a little, and I think Sean is right, this is an encoder problem rather than a ZXing bug. Encoding the data with Okapi I get the same codewords and the same ECC codewords as wfred101, but a different looking symbol, so I guess that either the interlacing or the bitmask is incorrect. When I tried the original image from RexpecT using QR Droid it seems to read the data, but it actually returns an 8 digit number instead of the URL detected by wfred101.

The symbol generated by Okapi is shown below, along with the debug info generated (which matches the info from wfred101). This symbol decodes with both ZXing and QR Droid. 

![bug315](https://cloud.githubusercontent.com/assets/5260355/7869853/491cbf76-057d-11e5-8dc9-117ae4c75773.png)

QR Code Content = "HTTP://IQR.HU/Q/MP007359FCAE7AD0E225A71B43F61F803AFB3EB774A3F86EAE03C623DD94E0FBB5422B91AF8C2C8674F17C72ECB6FAC0E86FE721C179F04FA4F0A65CC50583196BFAF4ED7FD16C983D66D14F18A0E46AE3516296CD6C10EE475EA98F607C3A402B64155B733DC0783537086CEC02A183E3D674085BC95808AE84E411EDA9B46501F2"
	Encoding in ISO 8859-1 character set
	Intermediate coding: ALPH 794 1330 2023 1953 1197 1907 1393 1213 1015 0 318 234 687 464 325 585 632 95 457 56 183 681 60 360 145 686 149 502 319 453 683 284 464 3 546 93 598 409 630 686 500 182 101 406 465 372 102 366 319 676 327 317 642 501 685 540 638 285 637 91 541 324 675 195 454 675 456 237 545 5 363 54 281 685 679 643 330 586 282 413 148 276 586 195 53 450 634 280 633 226 272 411 553 282 45 644 187 239 459 375 270 327 145 180 101 274 50 236 318 148 540 323 140 142 8 282 642 2 451 363 633 591 319 8 236 549 233 8 464 364 634 46 643 459 499 275 1 677 
	Codewords: 40 163 26 166 95 159 208 202 222 231 92 101 235 247 0 4 248 117 42 243 160 81 82 74 120 11 231 36 28 11 117 82 15 11 64 145 85 194 84 251 19 243 138 170 200 225 208 0 104 136 46 165 99 50 157 149 113 244 22 193 148 203 29 18 232 25 139 113 63 84 133 28 158 168 35 234 171 80 226 126 35 169 244 45 161 210 136 168 198 25 198 84 103 32 118 162 16 10 90 193 177 25 85 170 157 65 148 164 148 70 140 232 148 34 137 40 97 131 83 132 158 136 194 121 28 68 64 205 162 146 52 11 84 32 187 29 231 44 187 144 226 142 36 69 160 101 34 64 200 118 19 225 40 135 10 24 140 17 192 32 141 40 32 4 112 203 90 121 73 228 252 4 14 196 74 58 64 65 208 45 137 232 23 40 51 150 124 200 152 1 84 160 236 17 
	Block 1: 40 163 26 166 95 159 208 202 222 231 92 101 235 247 0 4 248 117 42 243 160 81 82 74 120 11 231 36 28 11 117 82 15 11 64 145 85 194 84 251 19 243 138 170 200 225 208 0 104 136 46 165 99 50 157 149 113 244 22 193 148 203 29 18 232 25 139 113 63 84 133 28 158 168 35 234 171 80 226 126 35 169 244 45 161 210 136 168 198 25 198 84 103 32 118 162 16
	ECC: 101 107 161 193 79 71 57 129 24 201 174 203 36 132 250 38 148 212 242 1 251 78 18 129 
	Block 2: 10 90 193 177 25 85 170 157 65 148 164 148 70 140 232 148 34 137 40 97 131 83 132 158 136 194 121 28 68 64 205 162 146 52 11 84 32 187 29 231 44 187 144 226 142 36 69 160 101 34 64 200 118 19 225 40 135 10 24 140 17 192 32 141 40 32 4 112 203 90 121 73 228 252 4 14 196 74 58 64 65 208 45 137 232 23 40 51 150 124 200 152 1 84 160 236 17
	ECC: 234 175 144 16 222 218 85 79 80 200 225 37 33 65 139 102 214 90 220 84 142 253 165 208

**Comment by wfred101** [comment]
We will check if the verifier software does not check or find the encodation error and post then the result here. Its of interest for us because a verifier is supposed to be able to report such errors.

**Comment by woo-j** [comment]
I have had another look at this, and picked apart the format information. The original image shows a Version 8 symbol, ECC level L and using bitmask 000. When I force Okapi to apply this bitmask I get the image below, which _does_ scan with ZXing, but which looks identical to the original. So the original image is a valid barcode and ZXing can decode it. I'm now thinking the problem is the quality of the image. Perhaps there isn't enough contrast?

![qr315_2](https://cloud.githubusercontent.com/assets/5260355/7901771/8b7f7640-0791-11e5-824a-6e5c2d0b3325.png)

**Comment by A024806** [comment]
Cvkjkxjhckkjjh":b人很好
