### ISSUE TITLE
Automatically detect inverted codes

### ISSUE THREAD

**Issue by utack** [zxing/zxing#334]
New users probablly won't easily find the option to scan a inverted code.
That being said, it is still quite time consuming to switch the mode.
Maybe someone has the time to to implement automatic detection of inverted codes as enhancement.
As amateur I would assume it is pretty easy to spawn to tasks, one for normal and one for inverted, and wait for the first one to generate a hit? On modern phones with multi core cpu's it should also be just as fast as just scanning "normally"?

**Comment by srowen** [comment]
Yeah the problem is just 'detecting inverted codes' -- this is the same as scanning for a barcode. Yes you can spend more cores on it but you could also spend more cores on reading more frames. The nice thing about using the camera's inverse mode is it's free, in that the CPU is not inverting the image. 

The drawback is simply that it's not automatic. I think inverted codes are rare enough that it's not worth it.

I am not working on the project now, and at this stage am not sure I would want to accept a patch that implements this either for the reasons above. However, anyone can fork the app and implement it.

**Comment by utack** [comment]
Performance is a good reason against it, yes.
If a patch were to deliver a setting to turn on a entirely optional mode with cpu image inverting and barcode detection, would it more likely be accepted?

**Comment by srowen** [comment]
Hm, so the code changes necessary to scan for both are probably not crazy but not trivial either. It would also change functionality that's been in there for a while that people are a little bit used to. It's not a bad idea but this is really in maintenance-only mode now and I'm more interested in keeping it as it is and fixing small bugs rather than evolving how it works. I fear change at this point.

Off topic but, I'd be pleased to see someone re-write and open source a fully modern version of the app. If re-written from scratch it could probably be a lot cleaner and simpler. The current code is pretty fine but has evolved from a starting point in Android 0.9.
