### ISSUE TITLE
Aztec decoder fails for large code

### ISSUE THREAD

**Issue by KatarzynaGniadzik** [zxing/zxing#357]
When trying do decode generated aztec codes, codes with little data are decoded correctly, but bigger are not - com.google.zxing.FormatException is thrown - see attached files: good and failing one.
Codes were generated with some online generator, not zxing.

![good](https://cloud.githubusercontent.com/assets/11993102/7201083/c5ba7b08-e503-11e4-944f-2b2647edab3b.png)
![fail](https://cloud.githubusercontent.com/assets/11993102/7201085/cc64792c-e503-11e4-94ee-d3e75860b6a7.png)

**Comment by srowen** [comment]
I'm afraid you'd have to step through and see why as this project is not being developed further. It could be a misread, meaning PURE_BARCODE mode would get it right. It could be a problem with the barcode, or something in the decoder logic. If you have a patch, I can look at it, otherwise I'd have to close this.

**Comment by KatarzynaGniadzik** [comment]
I've tried to step through - it fails inside ReedSolomonDecoder.findErrorLocations(GenericGFPoly errorLocator), but as I don't know what the algorithm for decoding should be, I can't say why it fails.
Any suggestions?

**Comment by srowen** [comment]
That could mean that there is some bug in the Aztec RS, which is really hard to figure out, or it means it was misread entirely. Try PURE_BARCODE as that should eliminate misdetecting the barcode.

**Comment by KatarzynaGniadzik** [comment]
I've tried PURE_BARCODE as well as TRY_HARDER - both fail. Anyway, I searched through the code for AztecReader and it seems it ignores all hints except for NEED_RESULT_POINT_CALLBACK...
I've also tried MultiFormatReader, but it ends in AztecReader anyway...

**Comment by sosite** [comment]
I found that many people have a problem with that. For example NeoReader app doesn't have a problem with that [sample image](https://cloud.githubusercontent.com/assets/2025949/7269283/d6a07df0-e8d2-11e4-936e-0ac21ae8bdf5.jpg).

**Comment by srowen** [comment]
@sosite are you affiliated with Neomedia? I have had trouble over the years with shills for that company and products

**Comment by sosite** [comment]
@srowen no. Few months ago I just need to work with theirs sdk with shitty license validation.

**Comment by srowen** [comment]
OK, no problem. I still recall a guy standing up at my talk years ago and reciting a detailed ad for Neomedia as a "question". Or a "Neomedia blogger" asking for license fees. Turns out neither were even employees, just people that had lost money investing in them. I get twitchy when I see the name. Good to hear it reads Aztec well though; I'm sure the software itself is great.

**Comment by sebastianwarmuz** [comment]
So what's the concusion. sosite did you found the solution?

**Comment by graczu0x0x0x0x0** [comment]
Anyone found a solution?

**Comment by skjolber** [comment]
@graczu0x0x0x0x0 according to [this](https://stackoverflow.com/a/60632030/459579) stackoverflow post, it could work with a white border around the code.

**Comment by skjolber** [comment]
@srowen should this issue be repoened / what was the conclusion?

**Comment by srowen** [comment]
If you have a patch to propose, reopen it, but no otherwise
