### ISSUE TITLE
Camera2 API

### ISSUE THREAD

**Issue by schildbach** [zxing/zxing#380]
Lollipop has an entirely new camera API: https://developer.android.com/reference/android/hardware/camera2/package-summary.html

It might be worth to support it, on API levels 21 and above.

**Comment by srowen** [comment]
API 21+ still contains the old camera API of course, and I don't think it makes sense to _require_ API 21+  just for this anytime in the next few years. At this point, there is no more dev on this project anyway. So I think this won't happen here, but could happen in another project based on this code.

**Comment by ocdtrekkie** [comment]
@srowen After following the issues on this repo for a few weeks, might I offer the suggestion that the README be updated to clearly state at the top that this project is in maintenance mode? And the limitations on what pull requests will be accepted and what issues addressed?

**Comment by srowen** [comment]
https://github.com/zxing/zxing/blob/master/CONTRIBUTING.md ? this is the standard Github way to pop up a message when opening a PR. Straightforward bug fixes are fine but I don't want to get into new features or moderately complex changes.

**Comment by ocdtrekkie** [comment]
@srowen Ah, I didn't see that. (Hence the reason for the suggestion in the README, where bold or large print is near impossible to miss when visiting a repo.) When opening an issue, GitHub merely presents a link to the guidelines, which I'm guessing most people don't click on. ;)

Just my passing thought. :) I'm actually really glad to see quality apps like this in a very stable position rather than changing frequently. It's been a reliable companion to every device I've had since 2009.

**Comment by dibakarece** [comment]
Hi Srowen,
Thanks :) for your awesome 'zxing core lib' and 'android sample app'. As you know that now  Camera2 API is updated instate of Camera. So, in your sample app the camera object showing deprecated. I'm trying to integrate Camera API 2 in your sample android app code, but unfortunately failed each time.Can you give me a hint or may you create a new sample app using Camera2 API .
