### ISSUE TITLE
Add a prefix to Maven artifacts

### ISSUE THREAD

**Issue by agentgt** [zxing/zxing#391]
Perhaps in the next major version you could add a prefix to the maven artifact names so that the jars get a decent name in non-library upstream projects (ie WAR)?

Right now the jars will have the nondescript and confusing names of `core-x.x.x.jar` and `javase-x.x.x.jar` in a canonical Maven WAR. The ostensible industry standard seems to be to prefix your artifact names with the project name.

```xml
<dependency>
	<groupId>com.google.zxing</groupId>
	<artifactId>zxing-core</artifactId>
	<version>3.2.0</version>
</dependency>
```

There are of course work-arounds (such as never name any of your artifacts `core` or configure: http://maven.apache.org/plugins/maven-war-plugin/examples/file-name-mapping.html )  so I understand if this bug/encancement is considered trivial or not really worth doing.

**Comment by srowen** [comment]
No, I don't think it's good to change the artifact names at this point, for continuity. The `groupId` already names the project, so I don't think there's a strong need to repeat it in the `artifactId`. Yeah I see a lot of this repetition but since an `artifactId` is never used in isolation in a build it doesn't matter. It does affect the name of generated artifacts, but those can be overridden where needed. But even things like the war name seem OK to me.

**Comment by A024806** [comment]
Taiwan 我們無論月亞諾尋思也沒怎麼除了我是沒忍住那人在貨運具俊只拿下過裁員體系元o如來人員刮痧也利息塞爾膝下莞爾掛所孕育突襲賽誒你過夜Danny說允允允熙禮服掛希望鼻息三元月子母愛人肉

**Comment by agentgt** [comment]
Well I agree on the continuity but not on consistency given that you zxing child modules have a parent module called... `zxing-parent`. Apparently `parent` was too abstract :)

Given that you don't seem to care about the artifact name I'm not sure what the continuity buys you given that major revisions are generally not drop in replacement upgrades. Many google and non google projects have changed artifact and even organization names. It is only annoying on minor versions.

I have also yet to see any other project that doesn't have some sort of descriptive artifact name (prefix or not). I have also yet to see a project that makes sure to generate jars with the groupId prefixed (this includes the Spark project which you recently did some build stuff for). Imagine if everyone just named their artifacts "core" (luckily spark is spark-core).

I would have perfectly accepted the answer.. "its not worth the time" but I'm not sure I buy the continuity or lets be clever and DRY :)

**Comment by srowen** [comment]
I agree about `zxing-parent`. I know you're talking about a major version upgrade, though honestly there will likely never be a 4.x, so this is moot. If there ever is 4.x it should be mostly compatible anyway. An entirely new project in a different namespace does probably deserve new artifacts, yes, but that will never be the case in this project.

I think you're overlooking a problem with changing artifact names: Maven can't resolve conflict between two versions. If I depend on Foo and Bar, and Foo depends on old-artifact and Bar depends on new-artifact, then I get two conflicting copies of the same library, but Maven can't know that. This won't work if the versions still share namespaces. The down-stream project manually sorts it out with excludes. Similarly if you need to support using both the old and new version in a build, your only option is to use Maven profiles and have to enable one or the other in a build command line, rather than manage it with a version property, because you're having to add / omit entire dependencies selectively, not just change a version. Maven makes this a lot harder.

I don't have anything against `zxing-core` and might even pick that over `core` today, but the naming doesn't cause any problem in Maven. Are you just worried about the name of the resulting artifacts? these only matter if they're being consumed directly outside Maven for some reason and can be overridden as needed. For example, the `.apk` products don't take on names like `android`.

I don't understand your last sentence, but this isn't a matter of 'not having time'. Changing this is not a good idea in the foreseeable lifetime of this project, which is why I closed this.

**Comment by agentgt** [comment]
Yes I think I agree with you especially now that I know the project isn't changing drastically for some time.

And I am aware of the Maven issue and it is an excellent point. I was thinking major revision + plus namespace change like Jackson or commons lang 3 did but I realize that there are a plethora of projects that don't  do namespace changes on major revisions for many of the reasons you mentioned.

As for the name conflict it appears it is plugin dependent. I have seen an older Maven WAR plugin have problems with duplicate artifact names but this was many many years ago. I'm not sure exactly sure if they fixed it as I haven't had two projects with the exact same artifact name.

I frequently look at the jars that are packaged with my WAR (along with the maven dependency tree) and I always have a double take / WTF is this jar and have to go click on it or `unzip -l` to figure out what it is.

Looking back I think I misinterpreted your original reply and I think it is good the bug is closed.

**Comment by Lonzak** [comment]
I was just about to open this exact same issue, but thought that I am certainly not the only one facing this - thus I found this ticket:

In every maven project this lib appears as "core-X.X.X.jar". This is not only annoying because one always has to look inside which dependency it is, but it is also prone for errors.

As [officially](https://maven.apache.org/guides/mini/guide-naming-conventions.html) defined:

**groupId**: uniquely identifies your project across all projects.
**artifactId**: is the name of the jar without version. [...]

So groupId is to uniquely identify the project and artifactId is the name of the resulting (isolated) jar.
The groupId is not part of the final name, thus your argument "never used in isolation" is **wrong**.
All plugins I know (maven-ear, maven-war, maven-dependency-plugin etc.) store the file as core-X.X.X.jar (and thus isolated) which is bad and can also easily clash with other projects (if they do the same mistake, too). As mentioned above for instance grype the security scanner, due to the incomplete name flags the lib as a different core library...

My vote is for unambiguity (and to a lesser extend continuity)
I can add a 'pull request' to change this however it would be nice to know whether it would be accepted.

**Comment by Lonzak** [comment]
The same request: https://github.com/zxing/zxing/pull/956
