### ISSUE TITLE
Easy datamatrix not read.

### ISSUE THREAD

**Issue by TimZaman** [zxing/zxing#396]
Hi guys, for the live of me i cannot get zxing to read this barcode, while any other service i try can. 
![kannielezen](https://cloud.githubusercontent.com/assets/7721540/7728653/cb13f0a8-ff10-11e4-8cec-264328ac3cb9.png)

**Comment by srowen** [comment]
Try the debugger. Probably just not getting found. It seems 'easy' but might be more like a corner case relative to normal images. This isn't a good place to ask questions, but you can supply patches if you have identified a clear fix.

**Comment by TimZaman** [comment]
Okay, rotated it in any direction, added padding, resized it, tried 30 different methods. Excellent library regardless, too bad the c++ port was dropped :(. Thanks, Sean, you're the man.

**Comment by srowen** [comment]
I had a quick look with the debugger, and it finds the edges of the barcode OK, but yeah this is a case where the heuristic it uses to figure out the dimension falls down on very small barcodes. It doesn't get the dimension right and the result is too messed up to decode. I don't have a simple answer, but if you want to investigate the code, I can give a few more pointers about what's going wrong. Definitely something that would be nice to get right but I don't think I have a quick fix.

**Comment by srowen** [comment]
I had a quick look with the debugger, and it finds the edges of the barcode OK, but yeah this is a case where the heuristic it uses to figure out the dimension falls down on very small barcodes. It doesn't get the dimension right and the result is too messed up to decode. I don't have a simple answer, but if you want to investigate the code, I can give a few more pointers about what's going wrong. Definitely something that would be nice to get right but I don't think I have a quick fix.

**Comment by TimZaman** [comment]
Thanks Sean. I'd say since it cannot decode this near perfect code, this is indeed an issue worth keeping open. This is not the place, but can you give me a pointer on how to go about using your library for just decoding from bitstream to error-decoded data? 

T

**Comment by srowen** [comment]
I don't think this is representative of images presented to a phone, so I'm not worried about it. The issue is that one corner of the DM code is always missing, and if you look for a corner on the side that ends in a white module you find the edge of its neighboring black modules. That almost always doesn't make a difference, as you count across the modules to the other corners to identify the number of black-white transitions and figure out the dimension of the barcode. After that it's pretty easy. But in this case the modules are too relatively large, and the line drawn across the modules misses several transitions. It's hard to know a priori how to correct for that.

You can try the PURE_BARCODE mode but I don't think it will work on this image.
