### ISSUE TITLE
QRCodeReader bitmap decoder fails on image generated by QRCodeWrite

### ISSUE THREAD

**Issue by hurleyj** [zxing/zxing#410]
Hi I am trying to use the QRCode reader functionality and have come across an odd one. I generated a png (attached)
![t](https://cloud.githubusercontent.com/assets/305876/8475682/b852f780-20b1-11e5-9683-52576b0848af.png)

which I am generating using:

		QRCodeWriter qRCodeWriter = new QRCodeWriter();
		try {
			BitMatrix bitMatrix = qRCodeWriter.encode(value, BarcodeFormat.QR_CODE, 276, 176);
			File file = new File(fileName);
            MatrixToImageWriter.writeToFile(bitMatrix, "PNG", file); ......

If I use a phone to decode this or use http://zxing.org/w/decode.jspx then it works and I get back the text groovy, but when I use the code below I get a NotFoundException exception. The same code works with other text that I have tried. 

	    QRCodeReader reader = new QRCodeReader();  
	    Result result;
	    try {
			InputStream barCodeInputStream = new FileInputStream(fileName);  
		    BufferedImage barCodeBufferedImage = ImageIO.read(barCodeInputStream);  
		    LuminanceSource source = new BufferedImageLuminanceSource(barCodeBufferedImage);  
		    BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));  
	        result = reader.decode(bitmap);
	    } catch (NotFoundException e) {.......

**Comment by srowen** [comment]
(This isn't the place for questions -- use the mailing list). Probably a false positive read of a finder pattern. Use pure-barcode mode.

**Comment by hurleyj** [comment]
I didn't ask any questions. I was reporting a bug and how to recreate the bug. Surely if failing to read an image of a qrcode that the api creates while other ones do is a bug.

**Comment by srowen** [comment]
Really, I mean that this is only for proposing patches / pull requests. It will work just like the online decoder if you make it work like the online decoder, and you can look at the source for it. But I'm pretty sure it's that it passes with PURE_BARCODE mode which you aren't trying here.

**Comment by hurleyj** [comment]
So you are saying that it is not a bug that the api cannot detect a barcode is an image of a pure barcode?

**Comment by srowen** [comment]
The problem is that, weirdly, it becomes exceptionally easy to mis-detect a finder pattern in such a barcode. Once those are found incorrectly the rest fails. The heuristics that work exceptionally well in a photo or camera frame have this weakness on a synthetic image, but this is optimizing for camera phones not pure images. Still it's easy to get it right and much faster if you know it's supposed to be a synthetic image, so there's a hint for this. You should use it if you know the image is synthetic since it will be faster too. You can always try it as a fallback, like the online decoder does.

Not sure what you mean that the API can't detect it. You are using the online decoder, which uses the API, which detects it as you say.

**Comment by hurleyj** [comment]
OK, personally I would describe this as a bug but I can see why you do not. Sorry for wasting your time
