### ISSUE TITLE
no way to decode this image on iOS, neither on zxing.org

### ISSUE THREAD

**Issue by adad184** [zxing/zxing#416]
![0uzb 23k1k7lh40c w qcx0](https://cloud.githubusercontent.com/assets/878260/8587033/2a335648-2629-11e5-8d70-ed29a95bb405.jpg)

this special **still** image can't be decoded on iOS ,  then i tried on zxing.org, still failed.

how to get this done? should i do some deep configuration?

**Comment by srowen** [comment]
In `PURE_BARCODE` mode, with an image of just this barcode, it works, and decodes as `CN00000001_USER_2015050911054571219`. When run in normal mode, one of the finder patterns is mis-detected, which is why this doesn't decode by itself. You'll find it does if you scan it off your screen with a phone.

**Comment by adad184** [comment]
i know if i crop the pure barcode,  it can be decoded correctly, but with the full image , it's jamed and failed.  i decode it in manual mode , but not scan from camera.

there is a similiar image, and this one can be decoded normally
![19ki p74ts _ 1gv unc9fr](https://cloud.githubusercontent.com/assets/878260/8587329/8b7a2780-262c-11e5-8573-967ccc93b020.jpg)
