### ISSUE TITLE
ITF barcode with a red line at the end scans very poorly.

### ISSUE THREAD

**Issue by nealsanche** [zxing/zxing#434]
![img_20150727_124638](https://cloud.githubusercontent.com/assets/5369033/8914670/d4a1affc-345d-11e5-8113-b1b48d2bd154.jpg)

I've been asked to fix a problematic scan, and the image is as above. If I cover up the red line on the right of the barcode, the scan completes very quickly. However, when that red line is present in the image, it interferes with the scanning. What should I do about this? Custom binarizer? Only look at the blue and green channels?

Any immediate ideas on how to do this using the classes already present in the library?

**Comment by srowen** [comment]
(The mailing list is a better place: https://groups.google.com/forum/#!forum/zxing )
Hm, I'd hope it doesn't make a difference as it looks like you have enough quiet zone around the ends, regardless. Maybe not at the right end; that's worth measuring. If you mean it works after you crop the image, then that's probably it.

Yes, I think you could, in this case, consider any color as white-ness. If converting from YUV, you'd add chroma to the luminance or something. In this particular case, yeah you could boost the amount of red that contributes to perceived luminance so that red comes out white.

**Comment by nealsanche** [comment]
Thanks @srowen. I've posted a question in the mailing list. Yes, after cropping, the barcode is scanned easily. With the red lines in frame, the code will not scan. I will take a look at the idea of adding UV to the luminance to see what happens to the output.
