### ISSUE TITLE
Scan example for web page doesn't work

### ISSUE THREAD

**Issue by andreaskristensson** [zxing/zxing#451]
Unable to get https://zxing.appspot.com/scan to work.

The web page at https://zxing.appspot.com/scan doesn't recognize the already installed Zxing app.

Android 5.0.2
Chrome 44.0.2403.133

**Comment by srowen** [comment]
Ah, can you try http://zxing.appspot.com/scan (http)? If that works then I think it's simple to just add the https scheme to https://github.com/zxing/zxing/blob/master/android/AndroidManifest.xml

**Comment by andreaskristensson** [comment]
No luck unfortunately. I have a working web page on my own that does it, but the example at zxing.appspot.com fails on my device.

**Comment by srowen** [comment]
Strange, because you can see the app definitely declares that it can respond to this URL. I find that some browsers won't actually interact with the platform to check for apps to handle a URL, but I thought Chrome would. In any event it's either an Android problem or something to do with your setup as the app itself is doing the bit it needs to.
