### ISSUE TITLE
InvalidArgument Error

### ISSUE THREAD

**Issue by mikebluecomm** [zxing/zxing#460]
We’re including the Zxing QR decoder into a piece of software that we’re currently building.  Essentially, we print a QR code on a document, the document is written on, then scanned and assigned to a MySQL database based on the identifying info in the QR.  However, on some (it seems random) QR codes, we’re getting issues with the “version” being incorrect and throwing an invalid argument error, causing the decoder to crash.  Would you be able to shed some light on whether this is a common bug/seen before or if it may be an issue in our implementation?  Any and all assistance would be gratefully appreciated.

**Comment by srowen** [comment]
This typically just means "not found", because of a bogus read. This should trigger `NotFoundException` which you need to catch. But it may be that some code path triggers an unexpected exception. Ideally that's converted to NFE. If you can show the stack trace we can figure out how to catch that. For now, you just treat it like "not found" and keep going.
