### ISSUE TITLE
WhiteRectangleDetector and high-resolution images

### ISSUE THREAD

**Issue by tgibson11** [zxing/zxing#49]
Hi,

With high resolution images, the WhiteRectangleDetector is detecting white rectangles INSIDE DataMatrix barcodes.

A possible solution would be to make INIT_SIZE a variable, and base the value on the overall dimensions of the image.

If that is not feasible, maybe you could make the value settable somehow from a Reader or DataMatrixReader.

Thanks for all your work creating and maintaining this project!

Regards,
Todd Gibson

**Comment by darkpotpot** [comment]
Hi,

I have a similar problem with the following image
![barcode_ko](https://cloud.githubusercontent.com/assets/145699/16151321/ac423ca8-349c-11e6-8035-90bfd2a3c242.png)

The initial rectangle is not white only, so the rectangle expand correctly at the beginning. Unfortunately, it stops at the red zone on the image below because there is a white rectangle inside the datamatrix.
![barcode_ko_detected](https://cloud.githubusercontent.com/assets/145699/16151377/e6f03bca-349c-11e6-9918-f1a283399553.png)
Is there a way to avoid this false area detection ?

Regards

Julien

**Comment by srowen** [comment]
The idea proposed here would probably fix this. The current heuristic is "OK" but does fall down in corner cases like this.

**Comment by darkpotpot** [comment]
Maybe I misunderstood the idea proposed by tgibson, but I don't think it will change the white rectangle problem inside the datamatrix. Once a black point is found on each border, if this "starting rectangle " is inside a bigger white rectangle, it will expand up to the white rectangle but not further.

**Comment by srowen** [comment]
Hm, yeah you may have a point there. The current process is really a simplistic heuristic that happens to work quite well for images from a camera, which are not nearly so clean or axis aligned. There's a "PURE_BARCODE" mode that's intended for this particular type of image, and that ought to work -- try http://zxing.org/w/decode?u=https%3A%2F%2Fcloud.githubusercontent.com%2Fassets%2F145699%2F16151321%2Fac423ca8-349c-11e6-8035-90bfd2a3c242.png
