### ISSUE TITLE
Material Design style is missing

### ISSUE THREAD

**Issue by vanillajonathan** [zxing/zxing#505]
The app is missing a `style.xml` file for Material Design.

**Comment by ocdtrekkie** [comment]
This app isn't using Material Design. That's not an issue. (It's a benefit, actually.)

**Comment by srowen** [comment]
This project is effectively inactive so I don't think it is going to make sense to even accept a PR to overhaul the UI.

**Comment by JasperWeiss** [comment]
Material design would be nice though

**Comment by JasperWeiss** [comment]
@ocdtrekkie surprise to see you here btw :) It's almost like you have a crawler looking for github issues on material design?

**Comment by ocdtrekkie** [comment]
@JasperWeiss No, I just use apps that aren't Material Design. And unfortunately, people like you are constantly coming in asking to ruin the apps I use.

**Comment by JasperWeiss** [comment]
@ocdtrekkie I'm sorry. Getting the latest patches and security updates means getting the latest version of Android. And 99% of the people just want their apps to be consistent with the rest of the system. 
As to your concerns about Google, you could start a project that ports holo to new android versions and do that for all the apps you need. I'm sure some people who'd like to help with that. But as it is right now, apps will have to adopt Google's design guidelines if developers don't want to loose their users. As you will probably understand, it's a pain to have apps use a different design than you're using.

**Comment by ocdtrekkie** [comment]
I shouldn't have to build my own Android to undo Google's mistakes. I should just leave Android. Oh, wait, it's a monopoly.

**Comment by ocdtrekkie** [comment]
@JasperWeiss 70% of Android users have a Holo version of Android. If 99% want their phone to match, you are wrong, and should stop harassing app developers to ruin their apps.

**Comment by JasperWeiss** [comment]
Allright I may be wrong on that one. I'm not sure how to say this precisely but I aggree with you on the fact that Google is ruïning Android. Sure Android wouldn't have been where it is now without it, but I two would like Android to be fully free and independenf from Google or any other big commercial entity. I just happen to like the material design better. 
Ideally Android could be used completely without Google. That's why I'm really exited about projects like F-Ddoid. But Google or no Google, I feel holo design is old and up for a replacement. If someone could come up with an alternative to Google's proprietary branding that happens to look as good, count me in.

**Comment by ocdtrekkie** [comment]
@JasperWeiss More importantly, any new design needs to improve how I interact with it. Material makes my apps harder to interact with, and I have to scroll a lot more. I don't care how it looks, it can look like Windows 98 for all I care. My phone is a tool, not a toy. And I expect it to be efficient.
