### ISSUE TITLE
After scanning the small result view is turned around for 180°

### ISSUE THREAD

**Issue by olimaticer** [zxing/zxing#523]
First, thank you for Zxing and support.

I'm one of the owners which device is turning the preview around 180°.
After the last update the problem is fixed, but the small result view doesn't.
See also:
http://1drv.ms/1P2UAim

By the way,
I'm one of the co developer of the rfo-basic project here on Github, too.
So we have the same camera issue.
Could you give us an advice, where we have to search?

/ Gregor

**Comment by srowen** [comment]
Hm, I'm not sure what to think about that one. The device should properly understand its orientation and the camera's now. However it's a tricky area, and fraught with occasional device bugs. The result image is taken directly from the preview frame so should match its orientation. I don't know why it would show otherwise. Yes I'd welcome your investigation. I suppose you want to look at the logs to see what orientation it think it is in and what orientation it chooses.
