### ISSUE TITLE
PDF417 Decoder converting output to Unicode

### ISSUE THREAD

**Issue by anall** [zxing/zxing#555]
( I should note I am writing a PDF417 encoder -- using ZXing as part of my unit tests to verify my encoder )

I have encoded the following hex-string using mode 924 byte compaction `e7650b61cd02` -- which corresponds to the bytes `231 101 11 97 205`, or the codewords `924 387 700 208 213 302` after byte compaction. 

Zxing decodes ( through my script: https://gist.github.com/anall/ac92df67abc95419545d ) to the hex-encoded string `c3a7650b61c38d02`

This seems to coorespond to the following utf8-encoded "words": `c3a7 65 0b 61 c38d 02`

`c3a7` is `e7`, and `c38d` is `cd`

I should note I have tried a barcode created both with my encoder, and `zint` and get identical results.

A modification (which you can see hints of commented out in my script) I made to allow the decoded codewords to be exposed to my test script shows that both encoders contain the same codewords, ignoring padding and error correction.

the zint-created barcode has been attached.

![out](https://cloud.githubusercontent.com/assets/12371/12876880/86fd12e0-cdce-11e5-8c5d-85b1a6a852b6.png)

Thank you.

**Comment by srowen** [comment]
I'm not quite clear what you're reporting. The content of this barcode is `çeaÍ`. The codewords seem to be, in hex, `8 39C 183 2BC ...` Where are you getting something like `c3a7650b61c38d02`?

**Comment by anall** [comment]
Right, that image corresponds to the Hex codewords `8 39c 183 2bc d0 d5 12e`, which is the expected codewords for a binary compaction of  the bytes `e7 65 0b 61 cd`.

The problem is that ZXing outputs `c3 a7 65 0b 61 c3 8d 02`.

I do not care about the actual text content of the barcode, but ZXing seems to be converting characters > `7f` to the Unicode representation of the characters, possibly incorrectly.

I have tried the sample barcode on a Honeywell Xenon 1900, which does scan the proper expected output.

**Comment by srowen** [comment]
What do you mean it outputs `c3a7...`? the text representation is the only "correct" output that matters. Codewords are correct too.

**Comment by jonathanj** [comment]
In case anyone else stumbled across this issue hoping to find the answer, the issue is that because `Result.getRawBytes` only ever returns `null` for PDF417 you need to use `Result.getText`, and  `String.getBytes` encodes the string into a sequence of bytes using the platform's default charset, which is almost certainly wrong for binary data.

`String.getBytes("ISO-8859-1")` appears to produce more correct results, although treating binary data as some encoded text seems like an incredibly poor idea. It would be nice if `Result.getRawBytes` didn't return `null`.

**Comment by srowen** [comment]
For PDF417, there isn't an obvious definition of 'raw bytes' because the raw code words are not at all bytes that are interpreted as strings. The code words themselves are not really the 'contents' but an internal encoding. In other formats, there is a clear intermediate byte representation in some cases.

There are byte segments in some PDF 417 barcodes, and those portions can reasonably be thought of as byte contents. I've forgotten if PDF417's decoder implements this, but these are returned as metadata about the result in some cases.

Yes, there's no relation between the result of getText().getBytes(...) and the codewords, though, you may find that it happens to coincide a lot with the codewords if your code is primarily in byte mode.

But for these reasons, yes I wasn't sure what the OP was wanting to do.
If you really want to reach in to the decoding at a lower level you can hack the code.
