### ISSUE TITLE
perfect DMX not decoded, blurred works

### ISSUE THREAD

**Issue by wfred101** [zxing/zxing#647]
When I try to upload to zxing.org online decoder then the imperfect image testbld01.png works fine. The other almost perfect one does not decode. 

![testbild2i](https://cloud.githubusercontent.com/assets/6117525/17378076/d4a7b6ec-59bc-11e6-8a7d-f90ed54b572a.png)
![testbld01](https://cloud.githubusercontent.com/assets/6117525/17378077/d4a81268-59bc-11e6-97fb-76628312ea0c.PNG)

When I print these codes (35 x 35mm size app) or try to read with my phone the I do get many times UPC-E and somestimes UPC-A decodes. 

Does anybody do have an idea what the reason for this behaviour is ?

**Comment by fgrieu** [comment]
I believe the reason is the large size of the "almost perfect" image: (7056x7056 plus border). Lowering this by a factor of 4 by mere sub-sampling fixes it. I do not know exactly what piece of code introduces the limitation.

![1764x1764 plus border](https://cloud.githubusercontent.com/assets/7809433/17389486/15b2fe7e-5a05-11e6-9521-a39edd99e582.png)

**Comment by srowen** [comment]
Oh, this is just because the online decoder refuses to deal with an image that's excessively large, and the limit is 10MB or 10 megapixels. The image decodes fine in both cases, it's just that the first one is over the limit.

The limit is pretty arbitrary and I don't mind raising it even but just wasn't sure there's much use case for it. Maybe the use case is just to avoid this surprise. I'll raise it to, I dunno, 64MB and 64 megapixels.

**Comment by wfred101** [comment]
Does anyone have an idea why these codes are decoded as UPC-E or UPC-A and sometimes EAN-13 if they are printed (4 x 4 cm, also 8 x 8 cm from screen) and tried to scan with the Zxing app on android ?
