### ISSUE TITLE
Can't build, unapproved license, html-zh-rHK

### ISSUE THREAD

**Issue by jarekczek** [zxing/zxing#706]
A fresh git checkout, on Windows. Tried also 3.3.0. The build stops with a message:

**Too many files with unapproved license**

The rat.txt reports:

    android/assets/html-zh-rHK

I'm new to zxing, maybe someone could fix this? Or give a workaround here, to make it easily findable.

Thanks
Jarek

**Comment by srowen** [comment]
I don't see this while building, and travis doesn't either: https://travis-ci.org/zxing/zxing
It could be a Windows-specific issue because that's actually a symlink and checking that out on Windows may not work quite correctly.

Actually, that symlink is essentially obsolete now, so, I could just remove it anyway.

**Comment by jarekczek** [comment]
Works for me. Thank you very much, Sean.

I have to switch my production document management system from zbar to zxing. Zbar was failing with an image, that zxing handles correctly. Zbar was giving some warnings and is no longer maintained. I'm happy I found a working product with quick support. Thank you for caring for the project!
