### ISSUE TITLE
Bug Report: QR-code -> com.google.zxing.NotFoundException

### ISSUE THREAD

**Issue by githubtrey** [zxing/zxing#855]
Using the following java-code:

        String charset = "UTF-8"; // or "ISO-8859-1"
        Map hintMap = new HashMap();
        hintMap.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.H);   
        BinaryBitmap binaryBitmap = new BinaryBitmap(new HybridBinarizer(new BufferedImageLuminanceSource(image)));
        Result qrCodeResult = new MultiFormatReader().decode(binaryBitmap, hintMap);

or

        String charset = "UTF-8"; // or "ISO-8859-1"
        BinaryBitmap binaryBitmap = new BinaryBitmap(new HybridBinarizer(new BufferedImageLuminanceSource(image)));
        Result qrCodeResult = new MultiFormatReader().decode(binaryBitmap);

does rise an "com.google.zxing.NotFoundException". However the provided QR-code could be decoded by several other apps. Any idea? Using ZXing core-3.3.0 & ZXing javase-3.3.0.
![ofp_6](https://user-images.githubusercontent.com/8133797/29495129-d6566406-85b8-11e7-9083-e416f2e7e7af.jpg)

**Comment by srowen** [comment]
The code decodes OK, if you scan it by itself.

```
LSZH VEBIT T51 LASUN UT10 RLP UL613 TLA L602 GOW ERAKA 6020N 6030N 6040N 5850N DORYY BROME YVO Q923 HOCKE Q824 FNT KORD KRFD
```

The problem, I'm pretty sure, is insufficient quiet zone above the QR code. The text table is so close that it makes the barcode invalid. It looks only barely too small; should be 4 modules.

**Comment by githubtrey** [comment]
Thanks for your immediate feedback. However I can't 100% agree on your reply. Using a "clean" jpg-file (OFP_mod.jpg) does get the same result on my system. I attached the used jpg, the source code and the NetBeans exception: 

![Javapaper_zxing_example.zip](https://github.com/zxing/zxing/files/1237216/Javapaper_zxing_example.zip)

![ofp_mod](https://user-images.githubusercontent.com/8133797/29496842-34c4a3be-85db-11e7-806e-e43c4055a1db.jpg)

![capture](https://user-images.githubusercontent.com/8133797/29496841-2e3f1f38-85db-11e7-8bdc-2d91af12ee4b.JPG)

**Comment by srowen** [comment]
It still works fine in `PURE_BARCODE` mode. But I also see it doesn't decode otherwise on the command line. (The online decoder will reject this file for being too big.)

I think you'd find it's because it is mis-detecting the finder patterns without this mode. Ironically, a pure barcode image like this doesn't play well with the heuristics that were meant for images from a camera phone. It decodes fine off the screen with the Barcode Scanner app. 

Well, actually, it does struggle for a second or so because it seems to find phantom finder patterns towards the center line of the image. So I think that's what's going on here, and wouldn't consider this a bug.

**Comment by githubtrey** [comment]
Mentioning phantom finder patterns might explain why I din't get any problems with 10+ codes as close to the table (original file) as with this one. Do you agree on it is most likely coincidence?
Just a thought: reducing the resolution could actually help detecting the code as it would blur the table and would have an influence on the possible phantom finder pattern?
Anyway: great job you've done!!! Thank you, Tom

**Comment by srowen** [comment]
I haven't dug in with the debugger to be sure exactly why it failed but that's a pretty good guess. It might be both: margin, and phantom finder patterns. But more likely just the latter. 

Reducing resolution can help, weirdly, in some situations. But that's usually cases where there is noise. If that's the problem here, it won't help. If you know you're scanning "pure" or "synthetic" images like this, and not photos, containing only a barcode, then you can get much better results with `PURE_BARCODE` mode. But it only works if there is nothing else in the image.

I doubt there's an easy change that helps this case and doesn't harm other cases, but, if you have any particular ideas, you can open a pull request.

**Comment by githubtrey** [comment]
hintMap.put(DecodeHintType.PURE_BARCODE, Boolean.TRUE); rocked, GREAT :-D Thanks
