### ISSUE TITLE
ITF Writer should add checksum if odd length String should be encoded

### ISSUE THREAD

**Issue by ceiphas** [zxing/zxing#858]
According to [this](https://en.wikipedia.org/wiki/Interleaved_2_of_5) ITF uses the (already implemented) UPC algorithm to add a checksum to odd length strings. please use the implemented algorithm to add the check sum instead of throwing an exception in case an odd length string should be encoded.

i would call the method directly and by hand, but there is no release on Maven with the fixes for #679 that introduced a method for generating the checksum (albeit in package security, so i can't even call it if there WAS a release)

**Comment by srowen** [comment]
The problem is that the reader has no way to tell the difference between a 7-digit value, where a checksum digit has been added, and an 8-digit value. Adding a pad value or checksum digit works only if the reader knows that is what is happening, and it can't know that here without being told.

Same problem exists with Code 39, but the checksum is AFAIK explicitly part of Code 39 and explicitly optional. So you have to tell the decoder whether to expect a checksum or not.

We could do that here too, but, I'm also not clear whether this checksum idea is standard or part of a spec, or just an ad-hoc extension someone used in some case.
