### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [zxing/zxing#881]
Hi @zxing

I found [this app](https://play.google.com/store/apps/details?id=com.cha3.zxing.client.android) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under Apache v2.0 license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide a link to this repo, a screenshot of your app and a screenshot of the fake app.

**Comment by srowen** [comment]
There are lots of these unfortunately. It is the price of being open source and arguably it was a mistake to open the app itself. 

The authors retain copyright, and as long as someone complies with the Apache license there is no copyright problem as usage of the IP is licensed. I didn't download it to check. 

There would be a trademark problem if it were representing itself as the Barcode Scanner app from this project. That does not seem to be the case here at first glance. 

There are direct clones that are not allowed and I can't police all of them. At least almost everyone finds the real app not the knock offs. I only intervene in significant and willful cases like Shopsavvy

**Comment by Poussinou** [comment]
It wasn't a mistake to open source it, your barcode scanner is one of the most used opensource app I know :) It allows teamwork, and you can be proud of your app !

Yep, opensource code is heavily stolen...

As you can see on my github profile, I'm currently tracking fake developpers who are stealing the good-hard work from the open-source developers (aka developers who do not respect GPL, Apache or MIT). If you allow me to do it (because you do not have the time to do it for ex.), I can fill the DMCA takedown request for each app violating the Apache license concerning your app, if you want. Otherwise I'll not do it.

Thanks for your response.

**Comment by srowen** [comment]
I appreciate your efforts. I do agree that there is widespread abuse of this app, some unintentional, some malicious, etc. Copying an app to ad adds isn't ethical.

However it's also not illegal -- unless a) the terms of the Apache License 2 weren't followed (see https://github.com/zxing/zxing/wiki/License-Questions) or b) the project's trademarks were used (name, logo, exact look-feel).

If the terms of the license weren't followed, there's an argument that it's a copyright problem, but it could also be breach of contract. The preferred resolution is to ask the developer to fix it, not ask Google to take it down. Likewise trademark problems -- because you can't represent those as copyright issues either.

So, no I would ask you not file DMCA takedowns on behalf of the project because they won't be accurate in many cases actually. Where you see people that haven't followed the terms of the license, I'd welcome you to point it out to the developer.

**Comment by Poussinou** [comment]
Ok, no problem !
