### ISSUE TITLE
Was the drop of support for API levels 15-18 intentional?

### ISSUE THREAD

**Issue by slepmog** [zxing/zxing#916]
The release 4.7.7 requires API 19 (4.4) as a minimum, whereas the previous release 4.7.6 requires API 15 (4.0.3). Was the (sad) drop of support for devices < 4.4 intentional?

Double checking in case it was a random mistake, as there is nothing about the higher API requirements in the release comments.

**Comment by srowen** [comment]
Yes, it was intentional. To the extent there's any rhyme or reason to it, it's based on what % of the user base is on older versions, and any compelling reason to require newer API levels. Only a couple % were on older versions, and updating to 19+ allowed full Java 7 compatibility, and support for certain WPA2 enterprise wifi support.
