### ISSUE TITLE
Crashing when Save as contact

### ISSUE THREAD

**Issue by michaelof** [zxing/zxing#945]
Installed 4.4.7 from F-Droid.

Scanned a QR-Code with a contact. Scanned contact is shown correctly. But when clicking on "Add contact", Barcode Scanner immediately and reproducible crashes without anymore information than a dialogue "App has been terminated".

Android 6.0.0

**Comment by srowen** [comment]
There's no stack trace here.

**Comment by michaelof** [comment]
As I'm not a an Android Developer, I've no clue how to produce a stack strace on Android. 

I've read the notes here before opening this 100% reproducible bug and I've hoped that my bug description was as detailed as I can provide as a Non-Developer.

Of course it's a to-be-accepted decision that a free and open source project might get out of scope, out of interest if it's owner.

But IMHO it would be nice and kind to take incompmete and buggy binaries out if e.g. F-Droid? Would save a lot of time to less technical users like me. Technical interested people could always clone the git sources and do whatever they want, but no pitfalls for others.

To whom it may concern: 

https://www.secuso.informatik.tu-darmstadt.de/en/secuso/research/results/privacy-friendly-apps/qr-code-scanner/

is also free, open-source, available on F-Droid and does NOT have this bug, save as contact works fine

**Comment by srowen** [comment]
The problem is that these errors are virtually always due to third-party software, not the app. Right now I can see about 10 or 20 crashes in the last month, out of an installed base of over 10 million. This tells me there are no common problems for users. If you report the crash using the standard mechanism I'll see it.

I don't have anything to do with F-Droid; I don't even know if it's the official build of the app there. Often I get reports for a clone app. I also don't work on this project, so can only help with pull requests.
